import type { ProductSeed } from "./seed-data";
import { strollerSpecs, carSeatSpecs, accessorySpecs } from "./seed-helpers";

// Espiro — польський бренд доступних колясок та автокрісел.
// Лінійки колясок: Next Avenue, Next Up, Only Way, Miloo, Sonic Air, Wave, Fuel, Rowan, Q5, Bueno.
// Автокрісла: Kappa (трансформер 0-36 кг), Beta (0+), Delta (бустер) + аксесуари.
export const espiroProducts: ProductSeed[] = [
  // --- Next Avenue (3в1) ---
  {
    slug: "espiro-next-avenue-grey",
    name_ua: "Коляска Espiro Next Avenue 3 в 1 (2026, Grey)",
    name_ru: "Коляска Espiro Next Avenue 3 в 1 (2026, Grey)",
    description_ua:
      "Espiro Next Avenue — доступний комплект 3 в 1 з люлькою, прогулянковим блоком та автокріслом групи 0+ в одній коробці. Велике колесо переднього поворотного модуля та амортизація на задній осі дають плавний хід навіть на бруківці.",
    description_ru:
      "Espiro Next Avenue — доступный комплект 3 в 1 с люлькой, прогулочным блоком и автокреслом группы 0+ в одной коробке. Большое поворотное переднее колесо и амортизация на задней оси обеспечивают плавный ход даже на брусчатке.",
    brand: "Espiro",
    category_slug: "strollers-3in1",
    price: 21000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.8 кг", "0–4 роки (з автокріслом)", "книжка", "гумові надувні"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "espiro-next-avenue-beige",
    name_ua: "Коляска Espiro Next Avenue 3 в 1 (2026, Beige)",
    name_ru: "Коляска Espiro Next Avenue 3 в 1 (2026, Beige)",
    description_ua:
      "Espiro Next Avenue — доступний комплект 3 в 1 з люлькою, прогулянковим блоком та автокріслом групи 0+ в одній коробці. Велике колесо переднього поворотного модуля та амортизація на задній осі дають плавний хід навіть на бруківці.",
    description_ru:
      "Espiro Next Avenue — доступный комплект 3 в 1 с люлькой, прогулочным блоком и автокреслом группы 0+ в одной коробке. Большое поворотное переднее колесо и амортизация на задней оси обеспечивают плавный ход даже на брусчатке.",
    brand: "Espiro",
    category_slug: "strollers-3in1",
    price: 21000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.8 кг", "0–4 роки (з автокріслом)", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-next-avenue-black",
    name_ua: "Коляска Espiro Next Avenue 3 в 1 (2026, Black)",
    name_ru: "Коляска Espiro Next Avenue 3 в 1 (2026, Black)",
    description_ua:
      "Espiro Next Avenue — доступний комплект 3 в 1 з люлькою, прогулянковим блоком та автокріслом групи 0+ в одній коробці. Велике колесо переднього поворотного модуля та амортизація на задній осі дають плавний хід навіть на бруківці.",
    description_ru:
      "Espiro Next Avenue — доступный комплект 3 в 1 с люлькой, прогулочным блоком и автокреслом группы 0+ в одной коробке. Большое поворотное переднее колесо и амортизация на задней оси обеспечивают плавный ход даже на брусчатке.",
    brand: "Espiro",
    category_slug: "strollers-3in1",
    price: 21500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.8 кг", "0–4 роки (з автокріслом)", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-next-avenue-denim",
    name_ua: "Коляска Espiro Next Avenue 3 в 1 (2026, Denim)",
    name_ru: "Коляска Espiro Next Avenue 3 в 1 (2026, Denim)",
    description_ua:
      "Espiro Next Avenue — доступний комплект 3 в 1 з люлькою, прогулянковим блоком та автокріслом групи 0+ в одній коробці. Велике колесо переднього поворотного модуля та амортизація на задній осі дають плавний хід навіть на бруківці.",
    description_ru:
      "Espiro Next Avenue — доступный комплект 3 в 1 с люлькой, прогулочным блоком и автокреслом группы 0+ в одной коробке. Большое поворотное переднее колесо и амортизация на задней оси обеспечивают плавный ход даже на брусчатке.",
    brand: "Espiro",
    category_slug: "strollers-3in1",
    price: 21500,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("13.8 кг", "0–4 роки (з автокріслом)", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-next-avenue-sand",
    name_ua: "Коляска Espiro Next Avenue 3 в 1 (2026, Sand)",
    name_ru: "Коляска Espiro Next Avenue 3 в 1 (2026, Sand)",
    description_ua:
      "Espiro Next Avenue — доступний комплект 3 в 1 з люлькою, прогулянковим блоком та автокріслом групи 0+ в одній коробці. Велике колесо переднього поворотного модуля та амортизація на задній осі дають плавний хід навіть на бруківці.",
    description_ru:
      "Espiro Next Avenue — доступный комплект 3 в 1 с люлькой, прогулочным блоком и автокреслом группы 0+ в одной коробке. Большое поворотное переднее колесо и амортизация на задней оси обеспечивают плавный ход даже на брусчатке.",
    brand: "Espiro",
    category_slug: "strollers-3in1",
    price: 21000,
    old_price: 24000,
    stock_status: "in_stock",
    specs: strollerSpecs("13.8 кг", "0–4 роки (з автокріслом)", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  // --- Next Up (2в1) ---
  {
    slug: "espiro-next-up-grey",
    name_ua: "Коляска Espiro Next Up 2 в 1 (Grey)",
    name_ru: "Коляска Espiro Next Up 2 в 1 (Grey)",
    description_ua:
      "Espiro Next Up — сучасніша сестра Next Avenue у форматі 2 в 1 без автокрісла в комплекті, для батьків, які вже мають своє. Легша рама та спрощений механізм складання роблять модель зручнішою для щоденного використання в місті.",
    description_ru:
      "Espiro Next Up — более современная сестра Next Avenue в формате 2 в 1 без автокресла в комплекте, для родителей, у которых оно уже есть. Более лёгкая рама и упрощённый механизм складывания делают модель удобнее для ежедневного использования в городе.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 19000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.5 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "espiro-next-up-beige",
    name_ua: "Коляска Espiro Next Up 2 в 1 (Beige)",
    name_ru: "Коляска Espiro Next Up 2 в 1 (Beige)",
    description_ua:
      "Espiro Next Up — сучасніша сестра Next Avenue у форматі 2 в 1 без автокрісла в комплекті, для батьків, які вже мають своє. Легша рама та спрощений механізм складання роблять модель зручнішою для щоденного використання в місті.",
    description_ru:
      "Espiro Next Up — более современная сестра Next Avenue в формате 2 в 1 без автокресла в комплекте, для родителей, у которых оно уже есть. Более лёгкая рама и упрощённый механизм складывания делают модель удобнее для ежедневного использования в городе.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 19000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.5 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-next-up-black",
    name_ua: "Коляска Espiro Next Up 2 в 1 (Black)",
    name_ru: "Коляска Espiro Next Up 2 в 1 (Black)",
    description_ua:
      "Espiro Next Up — сучасніша сестра Next Avenue у форматі 2 в 1 без автокрісла в комплекті, для батьків, які вже мають своє. Легша рама та спрощений механізм складання роблять модель зручнішою для щоденного використання в місті.",
    description_ru:
      "Espiro Next Up — более современная сестра Next Avenue в формате 2 в 1 без автокресла в комплекте, для родителей, у которых оно уже есть. Более лёгкая рама и упрощённый механизм складывания делают модель удобнее для ежедневного использования в городе.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 19500,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("12.5 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-next-up-denim",
    name_ua: "Коляска Espiro Next Up 2 в 1 (Denim)",
    name_ru: "Коляска Espiro Next Up 2 в 1 (Denim)",
    description_ua:
      "Espiro Next Up — сучасніша сестра Next Avenue у форматі 2 в 1 без автокрісла в комплекті, для батьків, які вже мають своє. Легша рама та спрощений механізм складання роблять модель зручнішою для щоденного використання в місті.",
    description_ru:
      "Espiro Next Up — более современная сестра Next Avenue в формате 2 в 1 без автокресла в комплекте, для родителей, у которых оно уже есть. Более лёгкая рама и упрощённый механизм складывания делают модель удобнее для ежедневного использования в городе.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 19500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.5 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Only Way (2в1) ---
  {
    slug: "espiro-only-way-denim",
    name_ua: "Коляска Espiro Only Way 2 в 1 (Denim)",
    name_ru: "Коляска Espiro Only Way 2 в 1 (Denim)",
    description_ua:
      "Espiro Only Way — бюджетна модульна коляска для тих, хто цінує практичність: люлька з жорстким дном і прогулянковий блок кріпляться на одне шасі без зайвих адаптерів. Знімні чохли легко прати в машинці.",
    description_ru:
      "Espiro Only Way — бюджетная модульная коляска для тех, кто ценит практичность: люлька с жёстким дном и прогулочный блок крепятся на одно шасси без лишних адаптеров. Съёмные чехлы легко стирать в машинке.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 16000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("11 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "espiro-only-way-grafit",
    name_ua: "Коляска Espiro Only Way 2 в 1 (Grafit)",
    name_ru: "Коляска Espiro Only Way 2 в 1 (Grafit)",
    description_ua:
      "Espiro Only Way — бюджетна модульна коляска для тих, хто цінує практичність: люлька з жорстким дном і прогулянковий блок кріпляться на одне шасі без зайвих адаптерів. Знімні чохли легко прати в машинці.",
    description_ru:
      "Espiro Only Way — бюджетная модульная коляска для тех, кто ценит практичность: люлька с жёстким дном и прогулочный блок крепятся на одно шасси без лишних адаптеров. Съёмные чехлы легко стирать в машинке.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 14000,
    old_price: 16000,
    stock_status: "in_stock",
    specs: strollerSpecs("11 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "espiro-only-way-beige",
    name_ua: "Коляска Espiro Only Way 2 в 1 (Beige)",
    name_ru: "Коляска Espiro Only Way 2 в 1 (Beige)",
    description_ua:
      "Espiro Only Way — бюджетна модульна коляска для тих, хто цінує практичність: люлька з жорстким дном і прогулянковий блок кріпляться на одне шасі без зайвих адаптерів. Знімні чохли легко прати в машинці.",
    description_ru:
      "Espiro Only Way — бюджетная модульная коляска для тех, кто ценит практичность: люлька с жёстким дном и прогулочный блок крепятся на одно шасси без лишних адаптеров. Съёмные чехлы легко стирать в машинке.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 16000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("11 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-only-way-black",
    name_ua: "Коляска Espiro Only Way 2 в 1 (Black)",
    name_ru: "Коляска Espiro Only Way 2 в 1 (Black)",
    description_ua:
      "Espiro Only Way — бюджетна модульна коляска для тих, хто цінує практичність: люлька з жорстким дном і прогулянковий блок кріпляться на одне шасі без зайвих адаптерів. Знімні чохли легко прати в машинці.",
    description_ru:
      "Espiro Only Way — бюджетная модульная коляска для тех, кто ценит практичность: люлька с жёстким дном и прогулочный блок крепятся на одно шасси без лишних адаптеров. Съёмные чехлы легко стирать в машинке.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 16000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("11 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Miloo (2в1, бюджетна) ---
  {
    slug: "espiro-miloo-blue",
    name_ua: "Коляска Espiro Miloo 2 в 1 (Blue)",
    name_ru: "Коляска Espiro Miloo 2 в 1 (Blue)",
    description_ua:
      "Espiro Miloo — бюджетна коляска 2 в 1 для батьків, які шукають простий і надійний варіант без зайвих опцій. Легка люлька та прогулянковий блок кріпляться на одне алюмінієве шасі за лічені секунди.",
    description_ru:
      "Espiro Miloo — бюджетная коляска 2 в 1 для родителей, которые ищут простой и надёжный вариант без лишних опций. Лёгкая люлька и прогулочный блок крепятся на одно алюминиевое шасси за считаные секунды.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 12000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.2 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-miloo-pink",
    name_ua: "Коляска Espiro Miloo 2 в 1 (Pink)",
    name_ru: "Коляска Espiro Miloo 2 в 1 (Pink)",
    description_ua:
      "Espiro Miloo — бюджетна коляска 2 в 1 для батьків, які шукають простий і надійний варіант без зайвих опцій. Легка люлька та прогулянковий блок кріпляться на одне алюмінієве шасі за лічені секунди.",
    description_ru:
      "Espiro Miloo — бюджетная коляска 2 в 1 для родителей, которые ищут простой и надёжный вариант без лишних опций. Лёгкая люлька и прогулочный блок крепятся на одно алюминиевое шасси за считаные секунды.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 12000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.2 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-miloo-grey",
    name_ua: "Коляска Espiro Miloo 2 в 1 (Grey)",
    name_ru: "Коляска Espiro Miloo 2 в 1 (Grey)",
    description_ua:
      "Espiro Miloo — бюджетна коляска 2 в 1 для батьків, які шукають простий і надійний варіант без зайвих опцій. Легка люлька та прогулянковий блок кріпляться на одне алюмінієве шасі за лічені секунди.",
    description_ru:
      "Espiro Miloo — бюджетная коляска 2 в 1 для родителей, которые ищут простой и надёжный вариант без лишних опций. Лёгкая люлька и прогулочный блок крепятся на одно алюминиевое шасси за считаные секунды.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 12500,
    old_price: null,
    stock_status: "out_of_stock",
    specs: strollerSpecs("10.2 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-miloo-beige",
    name_ua: "Коляска Espiro Miloo 2 в 1 (Beige)",
    name_ru: "Коляска Espiro Miloo 2 в 1 (Beige)",
    description_ua:
      "Espiro Miloo — бюджетна коляска 2 в 1 для батьків, які шукають простий і надійний варіант без зайвих опцій. Легка люлька та прогулянковий блок кріпляться на одне алюмінієве шасі за лічені секунди.",
    description_ru:
      "Espiro Miloo — бюджетная коляска 2 в 1 для родителей, которые ищут простой и надёжный вариант без лишних опций. Лёгкая люлька и прогулочный блок крепятся на одно алюминиевое шасси за считаные секунды.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 12500,
    old_price: 14000,
    stock_status: "in_stock",
    specs: strollerSpecs("10.2 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  // --- Sonic Air (прогулянкова) ---
  {
    slug: "espiro-sonic-air-mint",
    name_ua: "Коляска Espiro Sonic Air (Mint)",
    name_ru: "Коляска Espiro Sonic Air (Mint)",
    description_ua:
      "Espiro Sonic Air — легка прогулянкова коляска на надувних колесах за доступною ціною. Компактне складання «парасолька» та невелика вага роблять її зручною для поїздок громадським транспортом і подорожей.",
    description_ru:
      "Espiro Sonic Air — лёгкая прогулочная коляска на надувных колёсах по доступной цене. Компактное складывание «зонтик» и небольшой вес делают её удобной для поездок в общественном транспорте и путешествий.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 11000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.8 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "espiro-sonic-air-black",
    name_ua: "Коляска Espiro Sonic Air (Black)",
    name_ru: "Коляска Espiro Sonic Air (Black)",
    description_ua:
      "Espiro Sonic Air — легка прогулянкова коляска на надувних колесах за доступною ціною. Компактне складання «парасолька» та невелика вага роблять її зручною для поїздок громадським транспортом і подорожей.",
    description_ru:
      "Espiro Sonic Air — лёгкая прогулочная коляска на надувных колёсах по доступной цене. Компактное складывание «зонтик» и небольшой вес делают её удобной для поездок в общественном транспорте и путешествий.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 11000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.8 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-sonic-air-grey",
    name_ua: "Коляска Espiro Sonic Air (Grey)",
    name_ru: "Коляска Espiro Sonic Air (Grey)",
    description_ua:
      "Espiro Sonic Air — легка прогулянкова коляска на надувних колесах за доступною ціною. Компактне складання «парасолька» та невелика вага роблять її зручною для поїздок громадським транспортом і подорожей.",
    description_ru:
      "Espiro Sonic Air — лёгкая прогулочная коляска на надувных колёсах по доступной цене. Компактное складывание «зонтик» и небольшой вес делают её удобной для поездок в общественном транспорте и путешествий.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 11000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.8 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-sonic-air-red",
    name_ua: "Коляска Espiro Sonic Air (Red)",
    name_ru: "Коляска Espiro Sonic Air (Red)",
    description_ua:
      "Espiro Sonic Air — легка прогулянкова коляска на надувних колесах за доступною ціною. Компактне складання «парасолька» та невелика вага роблять її зручною для поїздок громадським транспортом і подорожей.",
    description_ru:
      "Espiro Sonic Air — лёгкая прогулочная коляска на надувных колёсах по доступной цене. Компактное складывание «зонтик» и небольшой вес делают её удобной для поездок в общественном транспорте и путешествий.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 11500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.8 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Wave (прогулянкова) ---
  {
    slug: "espiro-wave-red",
    name_ua: "Коляска Espiro Wave (Red)",
    name_ru: "Коляска Espiro Wave (Red)",
    description_ua:
      "Espiro Wave — найдоступніша прогулянкова коляска лінійки для щоденних коротких прогулянок. Проста конструкція без зайвих механізмів означає менше поломок і легкий ремонт.",
    description_ru:
      "Espiro Wave — самая доступная прогулочная коляска линейки для ежедневных коротких прогулок. Простая конструкция без лишних механизмов означает меньше поломок и лёгкий ремонт.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 7500,
    old_price: 9000,
    stock_status: "in_stock",
    specs: strollerSpecs("6.9 кг", "6 міс – 3 роки", "парасолька", "EVA пінополіуретанові"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "espiro-wave-navy",
    name_ua: "Коляска Espiro Wave (Navy)",
    name_ru: "Коляска Espiro Wave (Navy)",
    description_ua:
      "Espiro Wave — найдоступніша прогулянкова коляска лінійки для щоденних коротких прогулянок. Проста конструкція без зайвих механізмів означає менше поломок і легкий ремонт.",
    description_ru:
      "Espiro Wave — самая доступная прогулочная коляска линейки для ежедневных коротких прогулок. Простая конструкция без лишних механизмов означает меньше поломок и лёгкий ремонт.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 9000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("6.9 кг", "6 міс – 3 роки", "парасолька", "EVA пінополіуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-wave-black",
    name_ua: "Коляска Espiro Wave (Black)",
    name_ru: "Коляска Espiro Wave (Black)",
    description_ua:
      "Espiro Wave — найдоступніша прогулянкова коляска лінійки для щоденних коротких прогулянок. Проста конструкція без зайвих механізмів означає менше поломок і легкий ремонт.",
    description_ru:
      "Espiro Wave — самая доступная прогулочная коляска линейки для ежедневных коротких прогулок. Простая конструкция без лишних механизмов означает меньше поломок и лёгкий ремонт.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 9000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("6.9 кг", "6 міс – 3 роки", "парасолька", "EVA пінополіуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-wave-grey",
    name_ua: "Коляска Espiro Wave (Grey)",
    name_ru: "Коляска Espiro Wave (Grey)",
    description_ua:
      "Espiro Wave — найдоступніша прогулянкова коляска лінійки для щоденних коротких прогулянок. Проста конструкція без зайвих механізмів означає менше поломок і легкий ремонт.",
    description_ru:
      "Espiro Wave — самая доступная прогулочная коляска линейки для ежедневных коротких прогулок. Простая конструкция без лишних механизмов означает меньше поломок и лёгкий ремонт.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 9000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("6.9 кг", "6 міс – 3 роки", "парасолька", "EVA пінополіуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Fuel (прогулянкова, спортивна) ---
  {
    slug: "espiro-fuel-black",
    name_ua: "Коляска Espiro Fuel (Black)",
    name_ru: "Коляска Espiro Fuel (Black)",
    description_ua:
      "Espiro Fuel — прогулянкова коляска зі спортивним характером: збільшені колеса та посилена рама розраховані на активні прогулянки парком чи бездоріжжям. Спинка регулюється в трьох положеннях, а капюшон витягується для додаткового захисту від сонця.",
    description_ru:
      "Espiro Fuel — прогулочная коляска со спортивным характером: увеличенные колёса и усиленная рама рассчитаны на активные прогулки по парку или бездорожью. Спинка регулируется в трёх положениях, а капюшон вытягивается для дополнительной защиты от солнца.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 13000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.6 кг", "6 міс – 3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-fuel-red",
    name_ua: "Коляска Espiro Fuel (Red)",
    name_ru: "Коляска Espiro Fuel (Red)",
    description_ua:
      "Espiro Fuel — прогулянкова коляска зі спортивним характером: збільшені колеса та посилена рама розраховані на активні прогулянки парком чи бездоріжжям. Спинка регулюється в трьох положеннях, а капюшон витягується для додаткового захисту від сонця.",
    description_ru:
      "Espiro Fuel — прогулочная коляска со спортивным характером: увеличенные колёса и усиленная рама рассчитаны на активные прогулки по парку или бездорожью. Спинка регулируется в трёх положениях, а капюшон вытягивается для дополнительной защиты от солнца.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 13000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.6 кг", "6 міс – 3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-fuel-grey",
    name_ua: "Коляска Espiro Fuel (Grey)",
    name_ru: "Коляска Espiro Fuel (Grey)",
    description_ua:
      "Espiro Fuel — прогулянкова коляска зі спортивним характером: збільшені колеса та посилена рама розраховані на активні прогулянки парком чи бездоріжжям. Спинка регулюється в трьох положеннях, а капюшон витягується для додаткового захисту від сонця.",
    description_ru:
      "Espiro Fuel — прогулочная коляска со спортивным характером: увеличенные колёса и усиленная рама рассчитаны на активные прогулки по парку или бездорожью. Спинка регулируется в трёх положениях, а капюшон вытягивается для дополнительной защиты от солнца.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 13500,
    old_price: null,
    stock_status: "out_of_stock",
    specs: strollerSpecs("8.6 кг", "6 міс – 3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-fuel-navy",
    name_ua: "Коляска Espiro Fuel (Navy)",
    name_ru: "Коляска Espiro Fuel (Navy)",
    description_ua:
      "Espiro Fuel — прогулянкова коляска зі спортивним характером: збільшені колеса та посилена рама розраховані на активні прогулянки парком чи бездоріжжям. Спинка регулюється в трьох положеннях, а капюшон витягується для додаткового захисту від сонця.",
    description_ru:
      "Espiro Fuel — прогулочная коляска со спортивным характером: увеличенные колёса и усиленная рама рассчитаны на активные прогулки по парку или бездорожью. Спинка регулируется в трёх положениях, а капюшон вытягивается для дополнительной защиты от солнца.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 13500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.6 кг", "6 міс – 3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Rowan (3в1) ---
  {
    slug: "espiro-rowan-grey",
    name_ua: "Коляска Espiro Rowan 3 в 1 (Grey)",
    name_ru: "Коляска Espiro Rowan 3 в 1 (Grey)",
    description_ua:
      "Espiro Rowan — новинка лінійки з оновленим дизайном рами та збільшеним обʼємом кошика для покупок. Комплект 3 в 1 включає люльку з вентиляційними отворами, прогулянковий блок і автокрісло групи 0+.",
    description_ru:
      "Espiro Rowan — новинка линейки с обновлённым дизайном рамы и увеличенным объёмом корзины для покупок. Комплект 3 в 1 включает люльку с вентиляционными отверстиями, прогулочный блок и автокресло группы 0+.",
    brand: "Espiro",
    category_slug: "strollers-3in1",
    price: 23000,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("14 кг", "0–4 роки (з автокріслом)", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-rowan-beige",
    name_ua: "Коляска Espiro Rowan 3 в 1 (Beige)",
    name_ru: "Коляска Espiro Rowan 3 в 1 (Beige)",
    description_ua:
      "Espiro Rowan — новинка лінійки з оновленим дизайном рами та збільшеним обʼємом кошика для покупок. Комплект 3 в 1 включає люльку з вентиляційними отворами, прогулянковий блок і автокрісло групи 0+.",
    description_ru:
      "Espiro Rowan — новинка линейки с обновлённым дизайном рамы и увеличенным объёмом корзины для покупок. Комплект 3 в 1 включает люльку с вентиляционными отверстиями, прогулочный блок и автокресло группы 0+.",
    brand: "Espiro",
    category_slug: "strollers-3in1",
    price: 23500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14 кг", "0–4 роки (з автокріслом)", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Q5 (прогулянкова) ---
  {
    slug: "espiro-q5-beige",
    name_ua: "Коляска Espiro Q5 (Beige)",
    name_ru: "Коляска Espiro Q5 (Beige)",
    description_ua:
      "Espiro Q5 — прогулянкова коляска середнього класу з посиленими колесами та регульованою в трьох положеннях спинкою. Знімний чохол на ніжки та капюшон із додатковою вставкою захищають від вітру в прохолодну погоду.",
    description_ru:
      "Espiro Q5 — прогулочная коляска среднего класса с усиленными колёсами и спинкой, регулируемой в трёх положениях. Съёмный чехол на ножки и капюшон с дополнительной вставкой защищают от ветра в прохладную погоду.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 10500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.4 кг", "6 міс – 3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-q5-grey",
    name_ua: "Коляска Espiro Q5 (Grey)",
    name_ru: "Коляска Espiro Q5 (Grey)",
    description_ua:
      "Espiro Q5 — прогулянкова коляска середнього класу з посиленими колесами та регульованою в трьох положеннях спинкою. Знімний чохол на ніжки та капюшон із додатковою вставкою захищають від вітру в прохолодну погоду.",
    description_ru:
      "Espiro Q5 — прогулочная коляска среднего класса с усиленными колёсами и спинкой, регулируемой в трёх положениях. Съёмный чехол на ножки и капюшон с дополнительной вставкой защищают от ветра в прохладную погоду.",
    brand: "Espiro",
    category_slug: "strollers-buggy",
    price: 10500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.4 кг", "6 міс – 3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Bueno (2в1) ---
  {
    slug: "espiro-bueno-blue",
    name_ua: "Коляска Espiro Bueno 2 в 1 (Blue)",
    name_ru: "Коляска Espiro Bueno 2 в 1 (Blue)",
    description_ua:
      "Espiro Bueno поєднує класичну люльку з жорстким каркасом та прогулянковий блок на одному шасі за доступну ціну. Великий капюшон із віконцем дозволяє батькам стежити за дитиною під час сну на вулиці.",
    description_ru:
      "Espiro Bueno сочетает классическую люльку с жёстким каркасом и прогулочный блок на одном шасси по доступной цене. Большой капюшон с окошком позволяет родителям следить за ребёнком во время сна на улице.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 15000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.6 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-bueno-beige",
    name_ua: "Коляска Espiro Bueno 2 в 1 (Beige)",
    name_ru: "Коляска Espiro Bueno 2 в 1 (Beige)",
    description_ua:
      "Espiro Bueno поєднує класичну люльку з жорстким каркасом та прогулянковий блок на одному шасі за доступну ціну. Великий капюшон із віконцем дозволяє батькам стежити за дитиною під час сну на вулиці.",
    description_ru:
      "Espiro Bueno сочетает классическую люльку с жёстким каркасом и прогулочный блок на одном шасси по доступной цене. Большой капюшон с окошком позволяет родителям следить за ребёнком во время сна на улице.",
    brand: "Espiro",
    category_slug: "strollers-2in1",
    price: 15000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.6 кг", "0–3 роки", "книжка", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Kappa (автокрісло-трансформер 0-36 кг) ---
  {
    slug: "espiro-kappa-black",
    name_ua: "Автокрісло Espiro Kappa (Black)",
    name_ru: "Автокресло Espiro Kappa (Black)",
    description_ua:
      "Espiro Kappa — універсальне автокрісло-трансформер від народження до 36 кг, яке росте разом з дитиною через чотири групи без заміни на нове крісло. Встановлюється як проти ходу руху для немовлят, так і за ним для старших дітей.",
    description_ru:
      "Espiro Kappa — универсальное автокресло-трансформер от рождения до 36 кг, которое растёт вместе с ребёнком через четыре группы без замены на новое кресло. Устанавливается как против хода движения для младенцев, так и по ходу для детей постарше.",
    brand: "Espiro",
    category_slug: "car-seats-boosters",
    price: 9500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("11 кг", "0+/I/II/III (до 36 кг)", "ремені авто", "40–150 см"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "espiro-kappa-grey",
    name_ua: "Автокрісло Espiro Kappa (Grey)",
    name_ru: "Автокресло Espiro Kappa (Grey)",
    description_ua:
      "Espiro Kappa — універсальне автокрісло-трансформер від народження до 36 кг, яке росте разом з дитиною через чотири групи без заміни на нове крісло. Встановлюється як проти ходу руху для немовлят, так і за ним для старших дітей.",
    description_ru:
      "Espiro Kappa — универсальное автокресло-трансформер от рождения до 36 кг, которое растёт вместе с ребёнком через четыре группы без замены на новое кресло. Устанавливается как против хода движения для младенцев, так и по ходу для детей постарше.",
    brand: "Espiro",
    category_slug: "car-seats-boosters",
    price: 9500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("11 кг", "0+/I/II/III (до 36 кг)", "ремені авто", "40–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-kappa-blue",
    name_ua: "Автокрісло Espiro Kappa (Blue)",
    name_ru: "Автокресло Espiro Kappa (Blue)",
    description_ua:
      "Espiro Kappa — універсальне автокрісло-трансформер від народження до 36 кг, яке росте разом з дитиною через чотири групи без заміни на нове крісло. Встановлюється як проти ходу руху для немовлят, так і за ним для старших дітей.",
    description_ru:
      "Espiro Kappa — универсальное автокресло-трансформер от рождения до 36 кг, которое растёт вместе с ребёнком через четыре группы без замены на новое кресло. Устанавливается как против хода движения для младенцев, так и по ходу для детей постарше.",
    brand: "Espiro",
    category_slug: "car-seats-boosters",
    price: 10000,
    old_price: null,
    stock_status: "preorder",
    specs: carSeatSpecs("11 кг", "0+/I/II/III (до 36 кг)", "ремені авто", "40–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Beta (автокрісло 0+) ---
  {
    slug: "espiro-beta-black",
    name_ua: "Автокрісло Espiro Beta (Black)",
    name_ru: "Автокресло Espiro Beta (Black)",
    description_ua:
      "Espiro Beta — доступне автокрісло групи 0+ для перших поїздок немовляти з м'яким вкладишем для новонародженого. Встановлюється ременями безпеки авто і легко переноситься за ручку між домом і машиною.",
    description_ru:
      "Espiro Beta — доступное автокресло группы 0+ для первых поездок младенца с мягким вкладышем для новорождённого. Устанавливается ремнями безопасности авто и легко переносится за ручку между домом и машиной.",
    brand: "Espiro",
    category_slug: "car-seats-0plus",
    price: 5500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("3.4 кг", "0+ (до 13 кг)", "ремені авто", "40–75 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-beta-red",
    name_ua: "Автокрісло Espiro Beta (Red)",
    name_ru: "Автокресло Espiro Beta (Red)",
    description_ua:
      "Espiro Beta — доступне автокрісло групи 0+ для перших поїздок немовляти з м'яким вкладишем для новонародженого. Встановлюється ременями безпеки авто і легко переноситься за ручку між домом і машиною.",
    description_ru:
      "Espiro Beta — доступное автокресло группы 0+ для первых поездок младенца с мягким вкладышем для новорождённого. Устанавливается ремнями безопасности авто и легко переносится за ручку между домом и машиной.",
    brand: "Espiro",
    category_slug: "car-seats-0plus",
    price: 5500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("3.4 кг", "0+ (до 13 кг)", "ремені авто", "40–75 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Delta (бустер) ---
  {
    slug: "espiro-delta-grey",
    name_ua: "Автокрісло-бустер Espiro Delta (Grey)",
    name_ru: "Автокресло-бустер Espiro Delta (Grey)",
    description_ua:
      "Espiro Delta — простий бустер без спинки для дітей від 4 років, який піднімає дитину до рівня, де штатний ремінь авто лягає правильно. Легка конструкція дозволяє переставляти бустер між кількома автомобілями сім'ї.",
    description_ru:
      "Espiro Delta — простой бустер без спинки для детей от 4 лет, который поднимает ребёнка до уровня, где штатный ремень авто ложится правильно. Лёгкая конструкция позволяет переставлять бустер между несколькими автомобилями семьи.",
    brand: "Espiro",
    category_slug: "car-seats-boosters",
    price: 4500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("1.8 кг", "II/III (100–150 см)", "ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-delta-black",
    name_ua: "Автокрісло-бустер Espiro Delta (Black)",
    name_ru: "Автокресло-бустер Espiro Delta (Black)",
    description_ua:
      "Espiro Delta — простий бустер без спинки для дітей від 4 років, який піднімає дитину до рівня, де штатний ремінь авто лягає правильно. Легка конструкція дозволяє переставляти бустер між кількома автомобілями сім'ї.",
    description_ru:
      "Espiro Delta — простой бустер без спинки для детей от 4 лет, который поднимает ребёнка до уровня, где штатный ремень авто ложится правильно. Лёгкая конструкция позволяет переставлять бустер между несколькими автомобилями семьи.",
    brand: "Espiro",
    category_slug: "car-seats-boosters",
    price: 4500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("1.8 кг", "II/III (100–150 см)", "ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Аксесуари Espiro ---
  {
    slug: "espiro-changing-bag",
    name_ua: "Сумка для мами Espiro",
    name_ru: "Сумка для мамы Espiro",
    description_ua:
      "Містка сумка з кріпленнями на ручку коляски має окремі відділення для підгузків, пляшечок і особистих речей. У комплекті — водовідштовхувальний килимок для сповивання.",
    description_ru:
      "Вместительная сумка с креплениями на ручку коляски имеет отдельные отделения для подгузников, бутылочек и личных вещей. В комплекте — водоотталкивающий коврик для пеленания.",
    brand: "Espiro",
    category_slug: "accessories-stroller",
    price: 1800,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("водовідштовхувальний поліестер", "кріпиться на будь-яку ручку коляски", "протирати вологою тканиною"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-newborn-insert",
    name_ua: "Вкладиш для новонародженого Espiro",
    name_ru: "Вкладыш для новорождённого Espiro",
    description_ua:
      "М'який вкладиш підтримує голову й спину новонародженого в прогулянковому блоці або автокріслі, доки дитина не підросте. Знімний чохол легко прати при низькій температурі.",
    description_ru:
      "Мягкий вкладыш поддерживает голову и спину новорождённого в прогулочном блоке или автокресле, пока ребёнок не подрастёт. Съёмный чехол легко стирать при низкой температуре.",
    brand: "Espiro",
    category_slug: "accessories-carseat",
    price: 950,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("бавовна + поролон", "прогулянкові блоки та автокрісла групи 0+", "прання при 30°C"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-footmuff",
    name_ua: "Конверт зимовий Espiro",
    name_ru: "Конверт зимний Espiro",
    description_ua:
      "Утеплений конверт Espiro захищає ніжки дитини від холоду на зимових прогулянках і кріпиться до ременів безпеки коляски чи автокрісла. Знімна підкладка легко переться в машинці.",
    description_ru:
      "Утеплённый конверт Espiro защищает ножки ребёнка от холода на зимних прогулках и крепится к ремням безопасности коляски или автокресла. Съёмная подкладка легко стирается в машинке.",
    brand: "Espiro",
    category_slug: "footmuffs",
    price: 1600,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("плащівка + штучне хутро", "універсальний, з прорізами для ременів", "прання при 30°C"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-raincover",
    name_ua: "Дощовик універсальний Espiro",
    name_ru: "Дождевик универсальный Espiro",
    description_ua:
      "Дощовик Espiro захищає прогулянковий блок від дощу та вітру, залишаючись достатньо прозорим, щоб бачити дитину. Складається у компактний чохол і завжди поміщається в кошик коляски.",
    description_ru:
      "Дождевик Espiro защищает прогулочный блок от дождя и ветра, оставаясь достаточно прозрачным, чтобы видеть ребёнка. Складывается в компактный чехол и всегда помещается в корзину коляски.",
    brand: "Espiro",
    category_slug: "accessories-stroller",
    price: 400,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("ПВХ без запаху", "більшість прогулянкових колясок", "протирати вологою тканиною"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "espiro-mosquito-net",
    name_ua: "Москітна сітка Espiro",
    name_ru: "Москитная сетка Espiro",
    description_ua:
      "Москітна сітка Espiro натягується на капюшон і захищає дитину від комах у теплу пору року, не перекриваючи доступ повітря. Постачається в мішечку для зберігання разом з іншими аксесуарами.",
    description_ru:
      "Москитная сетка Espiro натягивается на капюшон и защищает ребёнка от насекомых в тёплое время года, не перекрывая доступ воздуха. Поставляется в мешочке для хранения вместе с другими аксессуарами.",
    brand: "Espiro",
    category_slug: "accessories-stroller",
    price: 320,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("поліестерна сітка", "більшість колясок", "ручне прання"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
];
