import type { ProductSeed } from "./seed-data";
import { strollerSpecs, carSeatSpecs, accessorySpecs } from "./seed-helpers";

// Anex — польський бренд модульних та прогулянкових колясок.
// Каталог зібраний за реальним прайс-листом офіційного дилера (RRP), фото — офіційні
// рендери з anexbaby.com (дилер авторизований використовувати їх для магазину).
// Лінійки: Flo, Mev, Eli, IQ, IQ Basic, e/type (спецсерії), L/type, Air-X², Air-Z plus,
// Air-Z, Air-X, автокрісло Cosmo, база Dock 2 + аксесуари.
export const anexProducts: ProductSeed[] = [
  // --- Flo (2 в 1) ---
  {
    slug: "anex-flo-solo",
    name_ua: "Коляска Anex Flo 2 в 1 (Solo)",
    name_ru: "Коляска Anex Flo 2 в 1 (Solo)",
    description_ua:
      "Anex Flo — компактна коляска 2 в 1 з люлькою та прогулянковим блоком на одному шасі. Легка алюмінієва рама складається одним рухом, а великий капюшон з вентиляційним віконцем захищає малюка від сонця та вітру.",
    description_ru:
      "Anex Flo — компактная коляска 2 в 1 с люлькой и прогулочным блоком на одном шасси. Лёгкая алюминиевая рама складывается одним движением, а большой капюшон с вентиляционным окошком защищает малыша от солнца и ветра.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.4 кг", "0–3 роки", "книжка одним рухом", "надувні гумові"),
    images: ["/products/anex/flo.jpg"],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "anex-flo-charm",
    name_ua: "Коляска Anex Flo 2 в 1 (Charm)",
    name_ru: "Коляска Anex Flo 2 в 1 (Charm)",
    description_ua:
      "Anex Flo — компактна коляска 2 в 1 з люлькою та прогулянковим блоком на одному шасі. Легка алюмінієва рама складається одним рухом, а великий капюшон з вентиляційним віконцем захищає малюка від сонця та вітру.",
    description_ru:
      "Anex Flo — компактная коляска 2 в 1 с люлькой и прогулочным блоком на одном шасси. Лёгкая алюминиевая рама складывается одним движением, а большой капюшон с вентиляционным окошком защищает малыша от солнца и ветра.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.4 кг", "0–3 роки", "книжка одним рухом", "надувні гумові"),
    images: ["/products/anex/flo.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-flo-yuki",
    name_ua: "Коляска Anex Flo 2 в 1 (Yuki)",
    name_ru: "Коляска Anex Flo 2 в 1 (Yuki)",
    description_ua:
      "Anex Flo — компактна коляска 2 в 1 з люлькою та прогулянковим блоком на одному шасі. Легка алюмінієва рама складається одним рухом, а великий капюшон з вентиляційним віконцем захищає малюка від сонця та вітру.",
    description_ru:
      "Anex Flo — компактная коляска 2 в 1 с люлькой и прогулочным блоком на одном шасси. Лёгкая алюминиевая рама складывается одним движением, а большой капюшон с вентиляционным окошком защищает малыша от солнца и ветра.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.4 кг", "0–3 роки", "книжка одним рухом", "надувні гумові"),
    images: ["/products/anex/flo.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-flo-astra",
    name_ua: "Коляска Anex Flo 2 в 1 (Astra)",
    name_ru: "Коляска Anex Flo 2 в 1 (Astra)",
    description_ua:
      "Anex Flo — компактна коляска 2 в 1 з люлькою та прогулянковим блоком на одному шасі. Легка алюмінієва рама складається одним рухом, а великий капюшон з вентиляційним віконцем захищає малюка від сонця та вітру.",
    description_ru:
      "Anex Flo — компактная коляска 2 в 1 с люлькой и прогулочным блоком на одном шасси. Лёгкая алюминиевая рама складывается одним движением, а большой капюшон с вентиляционным окошком защищает малыша от солнца и ветра.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("13.4 кг", "0–3 роки", "книжка одним рухом", "надувні гумові"),
    images: ["/products/anex/flo.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Mev (2 в 1) ---
  {
    slug: "anex-mev-ditto",
    name_ua: "Коляска Anex Mev 2 в 1 (Ditto)",
    name_ru: "Коляска Anex Mev 2 в 1 (Ditto)",
    description_ua:
      "Anex Mev поєднує глибоку люльку з вентиляцією та прогулянковий блок на посиленому шасі з великими колесами. Регульована по висоті ручка та місткий кошик роблять модель зручною для щоденних прогулянок містом.",
    description_ru:
      "Anex Mev сочетает глубокую люльку с вентиляцией и прогулочный блок на усиленном шасси с большими колёсами. Регулируемая по высоте ручка и вместительная корзина делают модель удобной для ежедневных прогулок по городу.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–3 роки", "книжка", "здвоєні поліуретанові"),
    images: ["/products/anex/mev.jpg"],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "anex-mev-kite",
    name_ua: "Коляска Anex Mev 2 в 1 (Kite)",
    name_ru: "Коляска Anex Mev 2 в 1 (Kite)",
    description_ua:
      "Anex Mev поєднує глибоку люльку з вентиляцією та прогулянковий блок на посиленому шасі з великими колесами. Регульована по висоті ручка та місткий кошик роблять модель зручною для щоденних прогулянок містом.",
    description_ru:
      "Anex Mev сочетает глубокую люльку с вентиляцией и прогулочный блок на усиленном шасси с большими колёсами. Регулируемая по высоте ручка и вместительная корзина делают модель удобной для ежедневных прогулок по городу.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–3 роки", "книжка", "здвоєні поліуретанові"),
    images: ["/products/anex/mev.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-mev-wink",
    name_ua: "Коляска Anex Mev 2 в 1 (Wink)",
    name_ru: "Коляска Anex Mev 2 в 1 (Wink)",
    description_ua:
      "Anex Mev поєднує глибоку люльку з вентиляцією та прогулянковий блок на посиленому шасі з великими колесами. Регульована по висоті ручка та місткий кошик роблять модель зручною для щоденних прогулянок містом.",
    description_ru:
      "Anex Mev сочетает глубокую люльку с вентиляцией и прогулочный блок на усиленном шасси с большими колёсами. Регулируемая по высоте ручка и вместительная корзина делают модель удобной для ежедневных прогулок по городу.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–3 роки", "книжка", "здвоєні поліуретанові"),
    images: ["/products/anex/mev.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Eli (2 в 1) ---
  {
    slug: "anex-eli-muse",
    name_ua: "Коляска Anex Eli 2 в 1 (Muse)",
    name_ru: "Коляска Anex Eli 2 в 1 (Muse)",
    description_ua:
      "Anex Eli — легша сестра Mev з тим самим модульним принципом: люлька та прогулянковий блок на одному алюмінієвому шасі. Підвіска на всіх колесах згладжує нерівності бруківки, а капюшон розтягується до самого бампера.",
    description_ru:
      "Anex Eli — облегчённая версия Mev с тем же модульным принципом: люлька и прогулочный блок на одном алюминиевом шасси. Подвеска на всех колёсах сглаживает неровности брусчатки, а капюшон растягивается до самого бампера.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 30990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.6 кг", "0–3 роки", "книжка", "надувні"),
    images: ["/products/anex/eli.jpg"],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "anex-eli-excite",
    name_ua: "Коляска Anex Eli 2 в 1 (Excite)",
    name_ru: "Коляска Anex Eli 2 в 1 (Excite)",
    description_ua:
      "Anex Eli — легша сестра Mev з тим самим модульним принципом: люлька та прогулянковий блок на одному алюмінієвому шасі. Підвіска на всіх колесах згладжує нерівності бруківки, а капюшон розтягується до самого бампера.",
    description_ru:
      "Anex Eli — облегчённая версия Mev с тем же модульным принципом: люлька и прогулочный блок на одном алюминиевом шасси. Подвеска на всех колёсах сглаживает неровности брусчатки, а капюшон растягивается до самого бампера.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 30990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.6 кг", "0–3 роки", "книжка", "надувні"),
    images: ["/products/anex/eli.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-eli-secret",
    name_ua: "Коляска Anex Eli 2 в 1 (Secret)",
    name_ru: "Коляска Anex Eli 2 в 1 (Secret)",
    description_ua:
      "Anex Eli — легша сестра Mev з тим самим модульним принципом: люлька та прогулянковий блок на одному алюмінієвому шасі. Підвіска на всіх колесах згладжує нерівності бруківки, а капюшон розтягується до самого бампера.",
    description_ru:
      "Anex Eli — облегчённая версия Mev с тем же модульным принципом: люлька и прогулочный блок на одном алюминиевом шасси. Подвеска на всех колёсах сглаживает неровности брусчатки, а капюшон растягивается до самого бампера.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 30990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.6 кг", "0–3 роки", "книжка", "надувні"),
    images: ["/products/anex/eli.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-eli-midnight",
    name_ua: "Коляска Anex Eli 2 в 1 (Midnight)",
    name_ru: "Коляска Anex Eli 2 в 1 (Midnight)",
    description_ua:
      "Anex Eli — легша сестра Mev з тим самим модульним принципом: люлька та прогулянковий блок на одному алюмінієвому шасі. Підвіска на всіх колесах згладжує нерівності бруківки, а капюшон розтягується до самого бампера.",
    description_ru:
      "Anex Eli — облегчённая версия Mev с тем же модульным принципом: люлька и прогулочный блок на одном алюминиевом шасси. Подвеска на всех колёсах сглаживает неровности брусчатки, а капюшон растягивается до самого бампера.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 30990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.6 кг", "0–3 роки", "книжка", "надувні"),
    images: ["/products/anex/eli.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-eli-santal",
    name_ua: "Коляска Anex Eli 2 в 1 (Santal)",
    name_ru: "Коляска Anex Eli 2 в 1 (Santal)",
    description_ua:
      "Anex Eli — легша сестра Mev з тим самим модульним принципом: люлька та прогулянковий блок на одному алюмінієвому шасі. Підвіска на всіх колесах згладжує нерівності бруківки, а капюшон розтягується до самого бампера.",
    description_ru:
      "Anex Eli — облегчённая версия Mev с тем же модульным принципом: люлька и прогулочный блок на одном алюминиевом шасси. Подвеска на всех колёсах сглаживает неровности брусчатки, а капюшон растягивается до самого бампера.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 30990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.6 кг", "0–3 роки", "книжка", "надувні"),
    images: ["/products/anex/eli.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-eli-no5",
    name_ua: "Коляска Anex Eli 2 в 1 (No.5)",
    name_ru: "Коляска Anex Eli 2 в 1 (No.5)",
    description_ua:
      "Спецсерія Anex Eli No.5 отримала ексклюзивне анодоване покриття рами та фірмове забарвлення текстилю в обмеженому накладі. Решта конструкції — та сама перевірена база Eli з люлькою та прогулянковим блоком.",
    description_ru:
      "Спецсерия Anex Eli No.5 получила эксклюзивное анодированное покрытие рамы и фирменную расцветку текстиля ограниченным тиражом. Остальная конструкция — та же проверенная база Eli с люлькой и прогулочным блоком.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 32990,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("12.8 кг", "0–3 роки", "книжка", "надувні"),
    images: ["/products/anex/eli.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- IQ (2 в 1, флагман) ---
  {
    slug: "anex-iq-smoky",
    name_ua: "Коляска Anex IQ 2 в 1 (Smoky)",
    name_ru: "Коляска Anex IQ 2 в 1 (Smoky)",
    description_ua:
      "Anex IQ — флагманська лінійка бренду з оновленим механізмом трансформації та рамою з авіаційного алюмінію. Панорамний капюшон з москітною сіткою та підсвіткою на колесах роблять вечірні прогулянки безпечнішими.",
    description_ru:
      "Anex IQ — флагманская линейка бренда с обновлённым механизмом трансформации и рамой из авиационного алюминия. Панорамный капюшон с москитной сеткой и подсветкой на колёсах делают вечерние прогулки безопаснее.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.6 кг", "0–3 роки", "книжка одним рухом", "надувні, з підвіскою"),
    images: ["/products/anex/iq.jpg"],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "anex-iq-pure",
    name_ua: "Коляска Anex IQ 2 в 1 (Pure)",
    name_ru: "Коляска Anex IQ 2 в 1 (Pure)",
    description_ua:
      "Anex IQ — флагманська лінійка бренду з оновленим механізмом трансформації та рамою з авіаційного алюмінію. Панорамний капюшон з москітною сіткою та підсвіткою на колесах роблять вечірні прогулянки безпечнішими.",
    description_ru:
      "Anex IQ — флагманская линейка бренда с обновлённым механизмом трансформации и рамой из авиационного алюминия. Панорамный капюшон с москитной сеткой и подсветкой на колёсах делают вечерние прогулки безопаснее.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.6 кг", "0–3 роки", "книжка одним рухом", "надувні, з підвіскою"),
    images: ["/products/anex/iq.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-iq-teddy",
    name_ua: "Коляска Anex IQ 2 в 1 (Teddy)",
    name_ru: "Коляска Anex IQ 2 в 1 (Teddy)",
    description_ua:
      "Anex IQ — флагманська лінійка бренду з оновленим механізмом трансформації та рамою з авіаційного алюмінію. Панорамний капюшон з москітною сіткою та підсвіткою на колесах роблять вечірні прогулянки безпечнішими.",
    description_ru:
      "Anex IQ — флагманская линейка бренда с обновлённым механизмом трансформации и рамой из авиационного алюминия. Панорамный капюшон с москитной сеткой и подсветкой на колёсах делают вечерние прогулки безопаснее.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.6 кг", "0–3 роки", "книжка одним рухом", "надувні, з підвіскою"),
    images: ["/products/anex/iq.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-iq-richi",
    name_ua: "Коляска Anex IQ 2 в 1 (Richi)",
    name_ru: "Коляска Anex IQ 2 в 1 (Richi)",
    description_ua:
      "Anex IQ — флагманська лінійка бренду з оновленим механізмом трансформації та рамою з авіаційного алюмінію. Панорамний капюшон з москітною сіткою та підсвіткою на колесах роблять вечірні прогулянки безпечнішими.",
    description_ru:
      "Anex IQ — флагманская линейка бренда с обновлённым механизмом трансформации и рамой из авиационного алюминия. Панорамный капюшон с москитной сеткой и подсветкой на колёсах делают вечерние прогулки безопаснее.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("14.6 кг", "0–3 роки", "книжка одним рухом", "надувні, з підвіскою"),
    images: ["/products/anex/iq.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-iq-seal",
    name_ua: "Коляска Anex IQ 2 в 1 (Seal)",
    name_ru: "Коляска Anex IQ 2 в 1 (Seal)",
    description_ua:
      "Anex IQ — флагманська лінійка бренду з оновленим механізмом трансформації та рамою з авіаційного алюмінію. Панорамний капюшон з москітною сіткою та підсвіткою на колесах роблять вечірні прогулянки безпечнішими.",
    description_ru:
      "Anex IQ — флагманская линейка бренда с обновлённым механизмом трансформации и рамой из авиационного алюминия. Панорамный капюшон с москитной сеткой и подсветкой на колёсах делают вечерние прогулки безопаснее.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 33990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.6 кг", "0–3 роки", "книжка одним рухом", "надувні, з підвіскою"),
    images: ["/products/anex/iq.jpg"],
    is_hit: true,
    is_sale: false,
  },
  // --- IQ Basic (спрощена версія IQ) ---
  {
    slug: "anex-iqbasic-nyx",
    name_ua: "Коляска Anex IQ Basic 2 в 1 (Nyx)",
    name_ru: "Коляска Anex IQ Basic 2 в 1 (Nyx)",
    description_ua:
      "Anex IQ Basic зберігає фірмову раму та трансформацію флагманської IQ, але без підсвітки коліс і частини преміум-опцій — вигідніший вибір для тих, кому важливіша функціональність, ніж технологічні дрібнички.",
    description_ru:
      "Anex IQ Basic сохраняет фирменную раму и трансформацию флагманской IQ, но без подсветки колёс и части премиум-опций — более выгодный выбор для тех, кому важнее функциональность, чем технологические мелочи.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 30990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14 кг", "0–3 роки", "книжка одним рухом", "надувні"),
    images: ["/products/anex/iq-basic.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-iqbasic-sienna",
    name_ua: "Коляска Anex IQ Basic 2 в 1 (Sienna)",
    name_ru: "Коляска Anex IQ Basic 2 в 1 (Sienna)",
    description_ua:
      "Anex IQ Basic зберігає фірмову раму та трансформацію флагманської IQ, але без підсвітки коліс і частини преміум-опцій — вигідніший вибір для тих, кому важливіша функціональність, ніж технологічні дрібнички.",
    description_ru:
      "Anex IQ Basic сохраняет фирменную раму и трансформацию флагманской IQ, но без подсветки колёс и части премиум-опций — более выгодный выбор для тех, кому важнее функциональность, чем технологические мелочи.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 30990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14 кг", "0–3 роки", "книжка одним рухом", "надувні"),
    images: ["/products/anex/iq-basic.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- e/type спецсерії (SALE) ---
  {
    slug: "anex-etype-art",
    name_ua: "Коляска Anex e/type 2 в 1 (Art)",
    name_ru: "Коляска Anex e/type 2 в 1 (Art)",
    description_ua:
      "Спецсерія Anex e/type Art — компактна коляска-трансформер з люлькою та прогулянковим блоком в ексклюзивному кольоровому виконанні обмеженого накладу. Складається одним рухом і поміщається в багажник компактного авто.",
    description_ru:
      "Спецсерия Anex e/type Art — компактная коляска-трансформер с люлькой и прогулочным блоком в эксклюзивном цветовом исполнении ограниченного тиража. Складывается одним движением и помещается в багажник компактного авто.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 25199,
    old_price: 27999,
    stock_status: "in_stock",
    specs: strollerSpecs("11.8 кг", "0–3 роки", "книжка одним рухом", "гумові надувні"),
    images: ["/products/anex/flo.jpg"],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "anex-etype-wilson",
    name_ua: "Коляска Anex e/type 2 в 1 (Wilson)",
    name_ru: "Коляска Anex e/type 2 в 1 (Wilson)",
    description_ua:
      "Спецсерія Anex e/type Wilson вирізняється анодованою рамою кольору бронзи та щільним твідовим текстилем. Люлька та прогулянковий блок в одному компактному шасі підійдуть від виписки з пологового до трьох років.",
    description_ru:
      "Спецсерия Anex e/type Wilson отличается анодированной рамой бронзового цвета и плотным твидовым текстилем. Люлька и прогулочный блок в одном компактном шасси подойдут от выписки из роддома до трёх лет.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 23399,
    old_price: 25999,
    stock_status: "in_stock",
    specs: strollerSpecs("11.8 кг", "0–3 роки", "книжка одним рухом", "гумові надувні"),
    images: ["/products/anex/flo.jpg"],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "anex-etype-joy",
    name_ua: "Коляска Anex e/type 2 в 1 (Joy)",
    name_ru: "Коляска Anex e/type 2 в 1 (Joy)",
    description_ua:
      "Спецсерія Anex e/type Joy — компактна коляска-трансформер з люлькою та прогулянковим блоком у життєрадісному кольоровому виконанні обмеженого накладу. Складається одним рухом і поміщається в багажник компактного авто.",
    description_ru:
      "Спецсерия Anex e/type Joy — компактная коляска-трансформер с люлькой и прогулочным блоком в жизнерадостном цветовом исполнении ограниченного тиража. Складывается одним движением и помещается в багажник компактного авто.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 25199,
    old_price: 27999,
    stock_status: "preorder",
    specs: strollerSpecs("11.8 кг", "0–3 роки", "книжка одним рухом", "гумові надувні"),
    images: ["/products/anex/flo.jpg"],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "anex-etype-eden",
    name_ua: "Коляска Anex e/type 2 в 1 (Eden)",
    name_ru: "Коляска Anex e/type 2 в 1 (Eden)",
    description_ua:
      "Спецсерія Anex e/type Eden поєднує анодовану раму та природну гаму текстилю. Люлька та прогулянковий блок в одному компактному шасі — практичний вибір для міських прогулянок без зайвих габаритів.",
    description_ru:
      "Спецсерия Anex e/type Eden сочетает анодированную раму и природную гамму текстиля. Люлька и прогулочный блок в одном компактном шасси — практичный выбор для городских прогулок без лишних габаритов.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 24299,
    old_price: 26999,
    stock_status: "in_stock",
    specs: strollerSpecs("11.8 кг", "0–3 роки", "книжка одним рухом", "гумові надувні"),
    images: ["/products/anex/flo.jpg"],
    is_hit: false,
    is_sale: true,
  },
  // --- L/type (2 в 1) ---
  {
    slug: "anex-ltype-frost",
    name_ua: "Коляска Anex L/type 2 в 1 (Frost)",
    name_ru: "Коляска Anex L/type 2 в 1 (Frost)",
    description_ua:
      "Anex L/type — нове покоління компактних колясок бренду з жорсткішою рамою та збільшеним кошиком для покупок. Люлька та прогулянковий блок легко міняються місцями на одному шасі без додаткових інструментів.",
    description_ru:
      "Anex L/type — новое поколение компактных колясок бренда с более жёсткой рамой и увеличенной корзиной для покупок. Люлька и прогулочный блок легко меняются местами на одном шасси без дополнительных инструментов.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 23169,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.9 кг", "0–3 роки", "книжка одним рухом", "надувні"),
    images: ["/products/anex/ltype.jpg"],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "anex-ltype-hazel",
    name_ua: "Коляска Anex L/type 2 в 1 (Hazel)",
    name_ru: "Коляска Anex L/type 2 в 1 (Hazel)",
    description_ua:
      "Anex L/type — нове покоління компактних колясок бренду з жорсткішою рамою та збільшеним кошиком для покупок. Люлька та прогулянковий блок легко міняються місцями на одному шасі без додаткових інструментів.",
    description_ru:
      "Anex L/type — новое поколение компактных колясок бренда с более жёсткой рамой и увеличенной корзиной для покупок. Люлька и прогулочный блок легко меняются местами на одном шасси без дополнительных инструментов.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 23169,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.9 кг", "0–3 роки", "книжка одним рухом", "надувні"),
    images: ["/products/anex/ltype.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-ltype-ocean",
    name_ua: "Коляска Anex L/type 2 в 1 (Ocean)",
    name_ru: "Коляска Anex L/type 2 в 1 (Ocean)",
    description_ua:
      "Anex L/type — нове покоління компактних колясок бренду з жорсткішою рамою та збільшеним кошиком для покупок. Люлька та прогулянковий блок легко міняються місцями на одному шасі без додаткових інструментів.",
    description_ru:
      "Anex L/type — новое поколение компактных колясок бренда с более жёсткой рамой и увеличенной корзиной для покупок. Люлька и прогулочный блок легко меняются местами на одном шасси без дополнительных инструментов.",
    brand: "Anex",
    category_slug: "strollers-2in1",
    price: 23169,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("13.9 кг", "0–3 роки", "книжка одним рухом", "надувні"),
    images: ["/products/anex/ltype.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Air-X² (легка прогулянкова) ---
  {
    slug: "anex-airx2-nero",
    name_ua: "Коляска Anex Air-X² (Nero)",
    name_ru: "Коляска Anex Air-X² (Nero)",
    description_ua:
      "Anex Air-X² складається одним рухом у компактний пакет, що стоїть самостійно, і легко поміщається в багажник будь-якого авто. Здвоєні колеса та розширена спинка з нахилом у горизонт підходять для денного сну на прогулянці.",
    description_ru:
      "Anex Air-X² складывается одним движением в компактный пакет, который стоит самостоятельно, и легко помещается в багажник любого авто. Сдвоенные колёса и расширенная спинка с наклоном в горизонт подходят для дневного сна на прогулке.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 13990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.4 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airx2.jpg"],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "anex-airx2-shiro",
    name_ua: "Коляска Anex Air-X² (Shiro)",
    name_ru: "Коляска Anex Air-X² (Shiro)",
    description_ua:
      "Anex Air-X² складається одним рухом у компактний пакет, що стоїть самостійно, і легко поміщається в багажник будь-якого авто. Здвоєні колеса та розширена спинка з нахилом у горизонт підходять для денного сну на прогулянці.",
    description_ru:
      "Anex Air-X² складывается одним движением в компактный пакет, который стоит самостоятельно, и легко помещается в багажник любого авто. Сдвоенные колёса и расширенная спинка с наклоном в горизонт подходят для дневного сна на прогулке.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 13990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.4 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airx2.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx2-vert",
    name_ua: "Коляска Anex Air-X² (Vert)",
    name_ru: "Коляска Anex Air-X² (Vert)",
    description_ua:
      "Anex Air-X² складається одним рухом у компактний пакет, що стоїть самостійно, і легко поміщається в багажник будь-якого авто. Здвоєні колеса та розширена спинка з нахилом у горизонт підходять для денного сну на прогулянці.",
    description_ru:
      "Anex Air-X² складывается одним движением в компактный пакет, который стоит самостоятельно, и легко помещается в багажник любого авто. Сдвоенные колёса и расширенная спинка с наклоном в горизонт подходят для дневного сна на прогулке.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 13990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.4 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airx2.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx2-bronzo",
    name_ua: "Коляска Anex Air-X² (Bronzo)",
    name_ru: "Коляска Anex Air-X² (Bronzo)",
    description_ua:
      "Anex Air-X² складається одним рухом у компактний пакет, що стоїть самостійно, і легко поміщається в багажник будь-якого авто. Здвоєні колеса та розширена спинка з нахилом у горизонт підходять для денного сну на прогулянці.",
    description_ru:
      "Anex Air-X² складывается одним движением в компактный пакет, который стоит самостоятельно, и легко помещается в багажник любого авто. Сдвоенные колёса и расширенная спинка с наклоном в горизонт подходят для дневного сна на прогулке.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 13990,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.4 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airx2.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx2-sky",
    name_ua: "Коляска Anex Air-X² (Sky)",
    name_ru: "Коляска Anex Air-X² (Sky)",
    description_ua:
      "Anex Air-X² складається одним рухом у компактний пакет, що стоїть самостійно, і легко поміщається в багажник будь-якого авто. Здвоєні колеса та розширена спинка з нахилом у горизонт підходять для денного сну на прогулянці.",
    description_ru:
      "Anex Air-X² складывается одним движением в компактный пакет, который стоит самостоятельно, и легко помещается в багажник любого авто. Сдвоенные колёса и расширенная спинка с наклоном в горизонт подходят для дневного сна на прогулке.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 13990,
    old_price: null,
    stock_status: "out_of_stock",
    specs: strollerSpecs("7.4 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airx2.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Air-Z plus (легка прогулянкова, розширена версія) ---
  {
    slug: "anex-airzplus-vivi",
    name_ua: "Коляска Anex Air-Z plus (Vivi)",
    name_ru: "Коляска Anex Air-Z plus (Vivi)",
    description_ua:
      "Anex Air-Z plus додає до перевіреної бази Air-Z ширше сидіння та збільшений кошик для покупок. Механізм складання одним рухом лишився таким самим компактним і зручним у поїздках.",
    description_ru:
      "Anex Air-Z plus добавляет к проверенной базе Air-Z более широкое сиденье и увеличенную корзину для покупок. Механизм складывания одним движением остался таким же компактным и удобным в поездках.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 14290,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.1 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airzplus.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airzplus-tillie",
    name_ua: "Коляска Anex Air-Z plus (Tillie)",
    name_ru: "Коляска Anex Air-Z plus (Tillie)",
    description_ua:
      "Anex Air-Z plus додає до перевіреної бази Air-Z ширше сидіння та збільшений кошик для покупок. Механізм складання одним рухом лишився таким самим компактним і зручним у поїздках.",
    description_ru:
      "Anex Air-Z plus добавляет к проверенной базе Air-Z более широкое сиденье и увеличенную корзину для покупок. Механизм складывания одним движением остался таким же компактным и удобным в поездках.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 14290,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.1 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airzplus.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Air-Z (легка прогулянкова) ---
  {
    slug: "anex-airz-space",
    name_ua: "Коляска Anex Air-Z (Space)",
    name_ru: "Коляска Anex Air-Z (Space)",
    description_ua:
      "Anex Air-Z — легка прогулянкова коляска з механізмом складання одним рухом, що стоїть самостійно навіть у складеному вигляді. Компактний пакет поміщається в багажник будь-якого авто чи в шафу в передпокої.",
    description_ru:
      "Anex Air-Z — лёгкая прогулочная коляска с механизмом складывания одним движением, которая стоит самостоятельно даже в сложенном виде. Компактный пакет помещается в багажник любого авто или в шкаф в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12490,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airz-omega",
    name_ua: "Коляска Anex Air-Z (Omega)",
    name_ru: "Коляска Anex Air-Z (Omega)",
    description_ua:
      "Anex Air-Z — легка прогулянкова коляска з механізмом складання одним рухом, що стоїть самостійно навіть у складеному вигляді. Компактний пакет поміщається в багажник будь-якого авто чи в шафу в передпокої.",
    description_ru:
      "Anex Air-Z — лёгкая прогулочная коляска с механизмом складывания одним движением, которая стоит самостоятельно даже в сложенном виде. Компактный пакет помещается в багажник любого авто или в шкаф в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12490,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airz-aurora",
    name_ua: "Коляска Anex Air-Z (Aurora)",
    name_ru: "Коляска Anex Air-Z (Aurora)",
    description_ua:
      "Anex Air-Z — легка прогулянкова коляска з механізмом складання одним рухом, що стоїть самостійно навіть у складеному вигляді. Компактний пакет поміщається в багажник будь-якого авто чи в шафу в передпокої.",
    description_ru:
      "Anex Air-Z — лёгкая прогулочная коляска с механизмом складывания одним движением, которая стоит самостоятельно даже в сложенном виде. Компактный пакет помещается в багажник любого авто или в шкаф в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12490,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airz-gelato",
    name_ua: "Коляска Anex Air-Z (Gelato)",
    name_ru: "Коляска Anex Air-Z (Gelato)",
    description_ua:
      "Anex Air-Z — легка прогулянкова коляска з механізмом складання одним рухом, що стоїть самостійно навіть у складеному вигляді. Компактний пакет поміщається в багажник будь-якого авто чи в шафу в передпокої.",
    description_ru:
      "Anex Air-Z — лёгкая прогулочная коляска с механизмом складывания одним движением, которая стоит самостоятельно даже в сложенном виде. Компактный пакет помещается в багажник любого авто или в шкаф в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12490,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airz-toasted",
    name_ua: "Коляска Anex Air-Z (Toasted)",
    name_ru: "Коляска Anex Air-Z (Toasted)",
    description_ua:
      "Anex Air-Z — легка прогулянкова коляска з механізмом складання одним рухом, що стоїть самостійно навіть у складеному вигляді. Компактний пакет поміщається в багажник будь-якого авто чи в шафу в передпокої.",
    description_ru:
      "Anex Air-Z — лёгкая прогулочная коляска с механизмом складывания одним движением, которая стоит самостоятельно даже в сложенном виде. Компактный пакет помещается в багажник любого авто или в шкаф в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12490,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airz-oaty",
    name_ua: "Коляска Anex Air-Z (Oaty)",
    name_ru: "Коляска Anex Air-Z (Oaty)",
    description_ua:
      "Anex Air-Z — легка прогулянкова коляска з механізмом складання одним рухом, що стоїть самостійно навіть у складеному вигляді. Компактний пакет поміщається в багажник будь-якого авто чи в шафу в передпокої.",
    description_ru:
      "Anex Air-Z — лёгкая прогулочная коляска с механизмом складывания одним движением, которая стоит самостоятельно даже в сложенном виде. Компактный пакет помещается в багажник любого авто или в шкаф в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12490,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airz-minted",
    name_ua: "Коляска Anex Air-Z (Minted)",
    name_ru: "Коляска Anex Air-Z (Minted)",
    description_ua:
      "Anex Air-Z — легка прогулянкова коляска з механізмом складання одним рухом, що стоїть самостійно навіть у складеному вигляді. Компактний пакет поміщається в багажник будь-якого авто чи в шафу в передпокої.",
    description_ru:
      "Anex Air-Z — лёгкая прогулочная коляска с механизмом складывания одним движением, которая стоит самостоятельно даже в сложенном виде. Компактный пакет помещается в багажник любого авто или в шкаф в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12490,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airz-arrr",
    name_ua: "Коляска Anex Air-Z (Arrr)",
    name_ru: "Коляска Anex Air-Z (Arrr)",
    description_ua:
      "Спецсерія Anex Air-Z Arrr — та сама легка база Air-Z у яскравому лімітованому забарвленні. Складається одним рухом і стоїть самостійно, не займаючи зайвого місця в передпокої.",
    description_ru:
      "Спецсерия Anex Air-Z Arrr — та же лёгкая база Air-Z в ярком лимитированном цветовом решении. Складывается одним движением и стоит самостоятельно, не занимая лишнего места в прихожей.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 13190,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("7.7 кг", "6 міс – 3 роки", "одним рухом, стоїть складена", "здвоєні поліуретанові"),
    images: ["/products/anex/airz.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Air-X (легка прогулянкова, попереднє покоління) ---
  {
    slug: "anex-airx-terracotta",
    name_ua: "Коляска Anex Air-X (Terracotta)",
    name_ru: "Коляска Anex Air-X (Terracotta)",
    description_ua:
      "Anex Air-X — перевірена часом легка коляска для активних батьків, яка складається парасолькою в компактний пакет за секунди. Надувні колеса пом'якшують нерівності бруківки та ґрунтових доріжок.",
    description_ru:
      "Anex Air-X — проверенная временем лёгкая коляска для активных родителей, которая складывается зонтиком в компактный пакет за секунды. Надувные колёса смягчают неровности брусчатки и грунтовых дорожек.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12899,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.2 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: ["/products/anex/airx.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx-gray",
    name_ua: "Коляска Anex Air-X (Gray)",
    name_ru: "Коляска Anex Air-X (Gray)",
    description_ua:
      "Anex Air-X — перевірена часом легка коляска для активних батьків, яка складається парасолькою в компактний пакет за секунди. Надувні колеса пом'якшують нерівності бруківки та ґрунтових доріжок.",
    description_ru:
      "Anex Air-X — проверенная временем лёгкая коляска для активных родителей, которая складывается зонтиком в компактный пакет за секунды. Надувные колёса смягчают неровности брусчатки и грунтовых дорожек.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12899,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.2 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: ["/products/anex/airx.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx-yellow",
    name_ua: "Коляска Anex Air-X (Yellow)",
    name_ru: "Коляска Anex Air-X (Yellow)",
    description_ua:
      "Anex Air-X — перевірена часом легка коляска для активних батьків, яка складається парасолькою в компактний пакет за секунди. Надувні колеса пом'якшують нерівності бруківки та ґрунтових доріжок.",
    description_ru:
      "Anex Air-X — проверенная временем лёгкая коляска для активных родителей, которая складывается зонтиком в компактный пакет за секунды. Надувные колёса смягчают неровности брусчатки и грунтовых дорожек.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12899,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.2 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: ["/products/anex/airx.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx-green",
    name_ua: "Коляска Anex Air-X (Green)",
    name_ru: "Коляска Anex Air-X (Green)",
    description_ua:
      "Anex Air-X — перевірена часом легка коляска для активних батьків, яка складається парасолькою в компактний пакет за секунди. Надувні колеса пом'якшують нерівності бруківки та ґрунтових доріжок.",
    description_ru:
      "Anex Air-X — проверенная временем лёгкая коляска для активных родителей, которая складывается зонтиком в компактный пакет за секунды. Надувные колёса смягчают неровности брусчатки и грунтовых дорожек.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12899,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.2 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: ["/products/anex/airx.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx-toffee",
    name_ua: "Коляска Anex Air-X (Toffee)",
    name_ru: "Коляска Anex Air-X (Toffee)",
    description_ua:
      "Anex Air-X — перевірена часом легка коляска для активних батьків, яка складається парасолькою в компактний пакет за секунди. Надувні колеса пом'якшують нерівності бруківки та ґрунтових доріжок.",
    description_ru:
      "Anex Air-X — проверенная временем лёгкая коляска для активных родителей, которая складывается зонтиком в компактный пакет за секунды. Надувные колёса смягчают неровности брусчатки и грунтовых дорожек.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12899,
    old_price: null,
    stock_status: "out_of_stock",
    specs: strollerSpecs("7.2 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: ["/products/anex/airx.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx-blue",
    name_ua: "Коляска Anex Air-X (Blue)",
    name_ru: "Коляска Anex Air-X (Blue)",
    description_ua:
      "Anex Air-X — перевірена часом легка коляска для активних батьків, яка складається парасолькою в компактний пакет за секунди. Надувні колеса пом'якшують нерівності бруківки та ґрунтових доріжок.",
    description_ru:
      "Anex Air-X — проверенная временем лёгкая коляска для активных родителей, которая складывается зонтиком в компактный пакет за секунды. Надувные колёса смягчают неровности брусчатки и грунтовых дорожек.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12899,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.2 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: ["/products/anex/airx.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-airx-avo",
    name_ua: "Коляска Anex Air-X (Avo)",
    name_ru: "Коляска Anex Air-X (Avo)",
    description_ua:
      "Anex Air-X — перевірена часом легка коляска для активних батьків, яка складається парасолькою в компактний пакет за секунди. Надувні колеса пом'якшують нерівності бруківки та ґрунтових доріжок.",
    description_ru:
      "Anex Air-X — проверенная временем лёгкая коляска для активных родителей, которая складывается зонтиком в компактный пакет за секунды. Надувные колёса смягчают неровности брусчатки и грунтовых дорожек.",
    brand: "Anex",
    category_slug: "strollers-buggy",
    price: 12899,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.2 кг", "6 міс – 3 роки", "парасолька", "надувні"),
    images: ["/products/anex/airx.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Автокрісло та база ---
  {
    slug: "anex-cosmo-black",
    name_ua: "Автокрісло Anex Cosmo (Black)",
    name_ru: "Автокресло Anex Cosmo (Black)",
    description_ua:
      "Autoкрісло Anex Cosmo групи 0+ створене у співпраці з Avionaut для перевезення немовлят від народження. Ергономічна чаша та знімна ручка для перенесення дозволяють переносити дитину, не розбудивши її.",
    description_ru:
      "Автокресло Anex Cosmo группы 0+ создано в сотрудничестве с Avionaut для перевозки младенцев с рождения. Эргономичная чаша и съёмная ручка для переноски позволяют перенести ребёнка, не разбудив его.",
    brand: "Anex",
    category_slug: "car-seats-0plus",
    price: 6490,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("3.6 кг", "0+ (0–13 кг)", "ремені авто / адаптери на шасі", "40–75 см"),
    images: ["/products/anex/cosmo.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-dock2-black",
    name_ua: "База ISOFIX Anex Dock 2 (Black)",
    name_ru: "База ISOFIX Anex Dock 2 (Black)",
    description_ua:
      "База Anex Dock 2 фіксується в авто через ISOFIX і опорну ногу з індикатором правильної установки. Автокрісло Cosmo клацає на базу за секунду, прибираючи потребу пристібати його ременями щоразу.",
    description_ru:
      "База Anex Dock 2 фиксируется в авто через ISOFIX и опорную ногу с индикатором правильной установки. Автокресло Cosmo защёлкивается на базу за секунду, убирая необходимость пристёгивать его ремнями каждый раз.",
    brand: "Anex",
    category_slug: "car-seat-bases",
    price: 6990,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("4.1 кг", "сумісна з автокріслом Cosmo 0+", "ISOFIX + опорна нога", "—"),
    images: ["/products/anex/dock2.jpg"],
    is_hit: false,
    is_sale: false,
  },
  // --- Аксесуари Anex ---
  {
    slug: "anex-muff-transformer",
    name_ua: "Муфта-трансформер для коляски Anex",
    name_ru: "Муфта-трансформер для коляски Anex",
    description_ua:
      "Муфта-трансформер Anex розкладається у повноцінний конверт для ніг або залишається компактною муфтою для рук — залежно від сезону. Хутряна обробка та водовідштовхувальна зовнішня тканина тримають тепло в холодні дні.",
    description_ru:
      "Муфта-трансформер Anex раскладывается в полноценный конверт для ног или остаётся компактной муфтой для рук — в зависимости от сезона. Меховая отделка и водоотталкивающая внешняя ткань сохраняют тепло в холодные дни.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 2750,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("плащівка + штучне хутро", "більшість колясок Anex", "прання при 30°C"),
    images: ["/products/anex/muff-transformer.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-footmuff-hug",
    name_ua: "Конверт фірмовий для коляски Anex HUG",
    name_ru: "Конверт фирменный для коляски Anex HUG",
    description_ua:
      "Утеплений конверт Anex HUG з м'якою підкладкою застібається навколо ремінців безпеки і не сповзає під час прогулянки. Розмір розрахований на дитину до трьох років, а знімна підкладка спрощує прання.",
    description_ru:
      "Утеплённый конверт Anex HUG с мягкой подкладкой застёгивается вокруг ремней безопасности и не сползает во время прогулки. Размер рассчитан на ребёнка до трёх лет, а съёмная подкладка упрощает стирку.",
    brand: "Anex",
    category_slug: "footmuffs",
    price: 3950,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("плащівка + флісова підкладка", "прогулянкові блоки Anex", "прання при 30°C"),
    images: ["/products/anex/footmuff-hug.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-footmuff-wom",
    name_ua: "Конверт фірмовий для коляски Anex WOM",
    name_ru: "Конверт фирменный для коляски Anex WOM",
    description_ua:
      "Конверт Anex WOM для люльки та автокрісла групи 0+ утеплює новонародженого без потреби розстібати ремені безпеки завдяки прорізам зі спеціальними блискавками. Зовнішня тканина відштовхує вологу під час снігу чи дощу.",
    description_ru:
      "Конверт Anex WOM для люльки и автокресла группы 0+ утепляет новорождённого без необходимости расстёгивать ремни безопасности благодаря прорезям со специальными молниями. Внешняя ткань отталкивает влагу во время снега или дождя.",
    brand: "Anex",
    category_slug: "footmuffs",
    price: 3850,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("плащівка + флісова підкладка", "люльки та автокрісла 0+ Anex", "прання при 30°C"),
    images: ["/products/anex/footmuff-wom.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-fur-hood",
    name_ua: "Хутряний капюшон для коляски Anex",
    name_ru: "Меховой капюшон для коляски Anex",
    description_ua:
      "Знімний хутряний капюшон на липучках одягається на край капюшона коляски за лічені секунди й додає додатковий захист від вітру обличчю дитини. Штучне хутро легко чиститься щіткою після прогулянки.",
    description_ru:
      "Съёмный меховой капюшон на липучках надевается на край капюшона коляски за считаные секунды и добавляет дополнительную защиту от ветра лицу ребёнка. Искусственный мех легко чистится щёткой после прогулки.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 1250,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("штучне хутро", "капюшони більшості колясок Anex", "чистити щіткою"),
    images: ["/products/anex/fur-hood.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-seat-liner",
    name_ua: "Вкладиш у прогулянковий блок універсальний Anex",
    name_ru: "Вкладыш в прогулочный блок универсальный Anex",
    description_ua:
      "Двобічний вкладиш Anex додає м'якості сидінню прогулянкового блока і має два кольорові боки на вибір настрою. Знімається без інструментів і переться в машинці разом з іншими дитячими речами.",
    description_ru:
      "Двусторонний вкладыш Anex добавляет мягкости сиденью прогулочного блока и имеет две цветные стороны на выбор настроения. Снимается без инструментов и стирается в машинке вместе с другими детскими вещами.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 2550,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("бавовна + поролон", "більшість прогулянкових блоків Anex", "прання при 30°C"),
    images: ["/products/anex/seat-liner.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-cup-holder-ct10",
    name_ua: "Підстаканник універсальний Anex CT10",
    name_ru: "Подстаканник универсальный Anex CT10",
    description_ua:
      "Підстаканник Anex CT10 кріпиться на поручень одним клацанням і надійно тримає пляшечку або чашку кави на прогулянці. Виготовлений з міцного пластику, стійкого до перепадів температур.",
    description_ru:
      "Подстаканник Anex CT10 крепится на поручень одним щелчком и надёжно удерживает бутылочку или чашку кофе на прогулке. Изготовлен из прочного пластика, устойчивого к перепадам температур.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 850,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("пластик", "більшість колясок з круглим поручнем", "мити в посудомийній машині"),
    images: ["/products/anex/cup-holder.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-umbrella",
    name_ua: "Парасолька для коляски Anex",
    name_ru: "Зонт для коляски Anex",
    description_ua:
      "Парасолька Anex кріпиться на раму коляски через універсальний затискач і повертається під потрібним кутом до сонця. Складається компактно й займає мінімум місця в кошику для покупок.",
    description_ru:
      "Зонт Anex крепится на раму коляски через универсальный зажим и поворачивается под нужным углом к солнцу. Складывается компактно и занимает минимум места в корзине для покупок.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 1190,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("поліестер + алюмінієва спиця", "більшість колясок з круглою рамою", "протирати вологою тканиною"),
    images: ["/products/anex/umbrella.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-shopping-bag",
    name_ua: "Сумка для покупок на коляску Anex",
    name_ru: "Сумка для покупок на коляску Anex",
    description_ua:
      "Сумка для покупок Anex кріпиться на раму під сидінням і розвантажує основний кошик коляски під час походу до магазину. Щільна тканина витримує вагу продуктів, а зручна ручка дозволяє носити сумку окремо.",
    description_ru:
      "Сумка для покупок Anex крепится на раму под сиденьем и разгружает основную корзину коляски во время похода в магазин. Плотная ткань выдерживает вес продуктов, а удобная ручка позволяет носить сумку отдельно.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 1190,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("щільний поліестер", "більшість колясок Anex", "ручне прання"),
    images: ["/products/anex/shopping-bag.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-iq-backpack",
    name_ua: "Рюкзак для коляски Anex IQ",
    name_ru: "Рюкзак для коляски Anex IQ",
    description_ua:
      "Фірмовий рюкзак Anex IQ кріпиться на ручку коляски і має термовідділення для пляшечок та окрему кишеню для дрібничок. Знімається за секунду й перетворюється на звичайний рюкзак для прогулянки без коляски.",
    description_ru:
      "Фирменный рюкзак Anex IQ крепится на ручку коляски и имеет термоотделение для бутылочек и отдельный карман для мелочей. Снимается за секунду и превращается в обычный рюкзак для прогулки без коляски.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 3290,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("водовідштовхувальний поліестер", "кріпиться на ручку коляски IQ та інших моделей", "протирати вологою тканиною"),
    images: ["/products/anex/iq-backpack.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-iq-mosquito-net",
    name_ua: "Москітна сітка Anex IQ",
    name_ru: "Москитная сетка Anex IQ",
    description_ua:
      "Дрібна москітна сітка для люльки та прогулянкового блока IQ захищає дитину від комах, не заважаючи циркуляції повітря. Натягується на капюшон гумками і складається в невеликий мішечок для зберігання.",
    description_ru:
      "Мелкая москитная сетка для люльки и прогулочного блока IQ защищает ребёнка от насекомых, не мешая циркуляции воздуха. Натягивается на капюшон резинками и складывается в небольшой мешочек для хранения.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 690,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("поліестерна сітка", "люлька та прогулянковий блок IQ", "ручне прання"),
    images: ["/products/anex/iq-mosquito.jpg"],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "anex-iq-raincover",
    name_ua: "Дощовик для колясок Anex IQ",
    name_ru: "Дождевик для колясок Anex IQ",
    description_ua:
      "Прозорий дощовик для прогулянкового блока IQ повністю закриває сидіння від дощу, залишаючи вентиляційні отвори для повітря. Компактно складається і завжди поміщається в кошик коляски про запас.",
    description_ru:
      "Прозрачный дождевик для прогулочного блока IQ полностью закрывает сиденье от дождя, оставляя вентиляционные отверстия для воздуха. Компактно складывается и всегда помещается в корзину коляски про запас.",
    brand: "Anex",
    category_slug: "accessories-stroller",
    price: 980,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("ПВХ без запаху", "прогулянковий блок IQ", "протирати вологою тканиною"),
    images: ["/products/anex/iq-raincover.jpg"],
    is_hit: false,
    is_sale: false,
  },
];
