import type { ProductSeed } from "./seed-data";
import { strollerSpecs, carSeatSpecs, accessorySpecs } from "./seed-helpers";

// Cybex — німецький бренд преміальних колясок та автокрісел.
// Лінійки колясок: Priam, e-Priam, Mios, Balios S Lux, Talos S Lux, Eezy S Twist+2,
// Beezy, Orfeo, Libelle, Coya, Gazelle S (single + duo для двійні).
// Автокрісла: Aton B2/S2, Cloud T (0+), Sirona T/S2/Gi (i-Size), Solution B2-Fix+/T i-Fix,
// Pallas G (бустери), Base T/One (бази ISOFIX) + аксесуари.
export const cybexProducts: ProductSeed[] = [
  // --- Priam (3в1) ---
  {
    slug: "cybex-priam-deep-black",
    name_ua: "Коляска Cybex Priam 3 в 1 (Deep Black)",
    name_ru: "Коляска Cybex Priam 3 в 1 (Deep Black)",
    description_ua:
      "Cybex Priam — культова коляска з хромованою чи матовою рамою на вибір та підвіскою One-Hand Fold, яка складає шасі одним рухом навіть з люлькою всередині. Магнітні застібки та преміальна тканина підкреслюють статус моделі.",
    description_ru:
      "Cybex Priam — культовая коляска с хромированной или матовой рамой на выбор и подвеской One-Hand Fold, которая складывает шасси одним движением даже с люлькой внутри. Магнитные застёжки и премиальная ткань подчёркивают статус модели.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 72000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "cybex-priam-nautical-blue",
    name_ua: "Коляска Cybex Priam 3 в 1 (Nautical Blue)",
    name_ru: "Коляска Cybex Priam 3 в 1 (Nautical Blue)",
    description_ua:
      "Cybex Priam — культова коляска з хромованою чи матовою рамою на вибір та підвіскою One-Hand Fold, яка складає шасі одним рухом навіть з люлькою всередині. Магнітні застібки та преміальна тканина підкреслюють статус моделі.",
    description_ru:
      "Cybex Priam — культовая коляска с хромированной или матовой рамой на выбор и подвеской One-Hand Fold, которая складывает шасси одним движением даже с люлькой внутри. Магнитные застёжки и премиальная ткань подчёркивают статус модели.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 72000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-priam-autumn-gold",
    name_ua: "Коляска Cybex Priam 3 в 1 (Autumn Gold)",
    name_ru: "Коляска Cybex Priam 3 в 1 (Autumn Gold)",
    description_ua:
      "Cybex Priam — культова коляска з хромованою чи матовою рамою на вибір та підвіскою One-Hand Fold, яка складає шасі одним рухом навіть з люлькою всередині. Магнітні застібки та преміальна тканина підкреслюють статус моделі.",
    description_ru:
      "Cybex Priam — культовая коляска с хромированной или матовой рамой на выбор и подвеской One-Hand Fold, которая складывает шасси одним движением даже с люлькой внутри. Магнитные застёжки и премиальная ткань подчёркивают статус модели.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 75000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-priam-chrome-black",
    name_ua: "Коляска Cybex Priam 3 в 1 (Chrome Black)",
    name_ru: "Коляска Cybex Priam 3 в 1 (Chrome Black)",
    description_ua:
      "Cybex Priam — культова коляска з хромованою чи матовою рамою на вибір та підвіскою One-Hand Fold, яка складає шасі одним рухом навіть з люлькою всередині. Магнітні застібки та преміальна тканина підкреслюють статус моделі.",
    description_ru:
      "Cybex Priam — культовая коляска с хромированной или матовой рамой на выбор и подвеской One-Hand Fold, которая складывает шасси одним движением даже с люлькой внутри. Магнитные застёжки и премиальная ткань подчёркивают статус модели.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 76000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-priam-pale-blush",
    name_ua: "Коляска Cybex Priam 3 в 1 (Pale Blush)",
    name_ru: "Коляска Cybex Priam 3 в 1 (Pale Blush)",
    description_ua:
      "Cybex Priam — культова коляска з хромованою чи матовою рамою на вибір та підвіскою One-Hand Fold, яка складає шасі одним рухом навіть з люлькою всередині. Магнітні застібки та преміальна тканина підкреслюють статус моделі.",
    description_ru:
      "Cybex Priam — культовая коляска с хромированной или матовой рамой на выбор и подвеской One-Hand Fold, которая складывает шасси одним движением даже с люлькой внутри. Магнитные застёжки и премиальная ткань подчёркивают статус модели.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 75000,
    old_price: 84000,
    stock_status: "in_stock",
    specs: strollerSpecs("14.2 кг", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "cybex-priam-soho-grey",
    name_ua: "Коляска Cybex Priam 3 в 1 (Soho Grey)",
    name_ru: "Коляска Cybex Priam 3 в 1 (Soho Grey)",
    description_ua:
      "Cybex Priam — культова коляска з хромованою чи матовою рамою на вибір та підвіскою One-Hand Fold, яка складає шасі одним рухом навіть з люлькою всередині. Магнітні застібки та преміальна тканина підкреслюють статус моделі.",
    description_ru:
      "Cybex Priam — культовая коляска с хромированной или матовой рамой на выбор и подвеской One-Hand Fold, которая складывает шасси одним движением даже с люлькой внутри. Магнитные застёжки и премиальная ткань подчёркивают статус модели.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 74000,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("14.2 кг", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- e-Priam (3в1, з електроприводом) ---
  {
    slug: "cybex-epriam-deep-black",
    name_ua: "Коляска Cybex e-Priam 3 в 1 (Deep Black)",
    name_ru: "Коляска Cybex e-Priam 3 в 1 (Deep Black)",
    description_ua:
      "Cybex e-Priam додає до культової рами Priam електропривід, який допомагає штовхати коляску вгору схилом і гальмує на спуску — досить натиснути кнопку на ручці. Батарея заряджається від звичайної розетки і витримує кілька днів щоденних прогулянок без підзарядки.",
    description_ru:
      "Cybex e-Priam добавляет к культовой раме Priam электропривод, который помогает толкать коляску в гору и тормозит на спуске — достаточно нажать кнопку на ручке. Батарея заряжается от обычной розетки и выдерживает несколько дней ежедневных прогулок без подзарядки.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 98000,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("16.9 кг (з батареєю)", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-epriam-pearl-grey-matt",
    name_ua: "Коляска Cybex e-Priam 3 в 1 (Pearl Grey Matt)",
    name_ru: "Коляска Cybex e-Priam 3 в 1 (Pearl Grey Matt)",
    description_ua:
      "Cybex e-Priam додає до культової рами Priam електропривід, який допомагає штовхати коляску вгору схилом і гальмує на спуску — досить натиснути кнопку на ручці. Батарея заряджається від звичайної розетки і витримує кілька днів щоденних прогулянок без підзарядки.",
    description_ru:
      "Cybex e-Priam добавляет к культовой раме Priam электропривод, который помогает толкать коляску в гору и тормозит на спуске — достаточно нажать кнопку на ручке. Батарея заряжается от обычной розетки и выдерживает несколько дней ежедневных прогулок без подзарядки.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 99000,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("16.9 кг (з батареєю)", "0–4 роки (з автокріслом)", "One-Hand Fold одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Mios (2в1 та 3в1) ---
  {
    slug: "cybex-mios-2in1-lava-red",
    name_ua: "Коляска Cybex Mios 2 в 1 (Lava Red)",
    name_ru: "Коляска Cybex Mios 2 в 1 (Lava Red)",
    description_ua:
      "Cybex Mios — найлегша модульна коляска бренду, зроблена з алюмінію авіаційного класу. Складається у компактний пакет однією рукою і легко переноситься за ремінець, а змінні дизайнерські панелі дозволяють освіжити вигляд без покупки нової коляски.",
    description_ru:
      "Cybex Mios — самая лёгкая модульная коляска бренда, выполненная из алюминия авиационного класса. Складывается в компактный пакет одной рукой и легко переносится за ремешок, а сменные дизайнерские панели позволяют освежить вид без покупки новой коляски.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 58000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.9 кг", "0–3 роки", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "cybex-mios-2in1-soho-grey",
    name_ua: "Коляска Cybex Mios 2 в 1 (Soho Grey)",
    name_ru: "Коляска Cybex Mios 2 в 1 (Soho Grey)",
    description_ua:
      "Cybex Mios — найлегша модульна коляска бренду, зроблена з алюмінію авіаційного класу. Складається у компактний пакет однією рукою і легко переноситься за ремінець, а змінні дизайнерські панелі дозволяють освіжити вигляд без покупки нової коляски.",
    description_ru:
      "Cybex Mios — самая лёгкая модульная коляска бренда, выполненная из алюминия авиационного класса. Складывается в компактный пакет одной рукой и легко переносится за ремешок, а сменные дизайнерские панели позволяют освежить вид без покупки новой коляски.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 52000,
    old_price: 58000,
    stock_status: "in_stock",
    specs: strollerSpecs("10.9 кг", "0–3 роки", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "cybex-mios-2in1-sepia-black",
    name_ua: "Коляска Cybex Mios 2 в 1 (Sepia Black)",
    name_ru: "Коляска Cybex Mios 2 в 1 (Sepia Black)",
    description_ua:
      "Cybex Mios — найлегша модульна коляска бренду, зроблена з алюмінію авіаційного класу. Складається у компактний пакет однією рукою і легко переноситься за ремінець, а змінні дизайнерські панелі дозволяють освіжити вигляд без покупки нової коляски.",
    description_ru:
      "Cybex Mios — самая лёгкая модульная коляска бренда, выполненная из алюминия авиационного класса. Складывается в компактный пакет одной рукой и легко переносится за ремешок, а сменные дизайнерские панели позволяют освежить вид без покупки новой коляски.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 58000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.9 кг", "0–3 роки", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-mios-2in1-cozy-beige",
    name_ua: "Коляска Cybex Mios 2 в 1 (Cozy Beige)",
    name_ru: "Коляска Cybex Mios 2 в 1 (Cozy Beige)",
    description_ua:
      "Cybex Mios — найлегша модульна коляска бренду, зроблена з алюмінію авіаційного класу. Складається у компактний пакет однією рукою і легко переноситься за ремінець, а змінні дизайнерські панелі дозволяють освіжити вигляд без покупки нової коляски.",
    description_ru:
      "Cybex Mios — самая лёгкая модульная коляска бренда, выполненная из алюминия авиационного класса. Складывается в компактный пакет одной рукой и легко переносится за ремешок, а сменные дизайнерские панели позволяют освежить вид без покупки новой коляски.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 58500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.9 кг", "0–3 роки", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-mios-3in1-sepia-black",
    name_ua: "Коляска Cybex Mios 3 в 1 (Sepia Black)",
    name_ru: "Коляска Cybex Mios 3 в 1 (Sepia Black)",
    description_ua:
      "Комплект Cybex Mios 3 в 1 додає до фірмової легкої рами автокрісло групи 0+ із системою кріплення без бази. Це рішення для сімей, яким потрібна одна коляска на всі випадки — від пологового будинку до поїздок на авто.",
    description_ru:
      "Комплект Cybex Mios 3 в 1 добавляет к фирменной лёгкой раме автокресло группы 0+ с системой крепления без базы. Это решение для семей, которым нужна одна коляска на все случаи — от роддома до поездок на авто.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 63000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.4 кг", "0–4 роки (з автокріслом)", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-mios-3in1-soho-grey",
    name_ua: "Коляска Cybex Mios 3 в 1 (Soho Grey)",
    name_ru: "Коляска Cybex Mios 3 в 1 (Soho Grey)",
    description_ua:
      "Комплект Cybex Mios 3 в 1 додає до фірмової легкої рами автокрісло групи 0+ із системою кріплення без бази. Це рішення для сімей, яким потрібна одна коляска на всі випадки — від пологового будинку до поїздок на авто.",
    description_ru:
      "Комплект Cybex Mios 3 в 1 добавляет к фирменной лёгкой раме автокресло группы 0+ с системой крепления без базы. Это решение для семей, которым нужна одна коляска на все случаи — от роддома до поездок на авто.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 64000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("12.4 кг", "0–4 роки (з автокріслом)", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-mios-3in1-lava-red",
    name_ua: "Коляска Cybex Mios 3 в 1 (Lava Red)",
    name_ru: "Коляска Cybex Mios 3 в 1 (Lava Red)",
    description_ua:
      "Комплект Cybex Mios 3 в 1 додає до фірмової легкої рами автокрісло групи 0+ із системою кріплення без бази. Це рішення для сімей, яким потрібна одна коляска на всі випадки — від пологового будинку до поїздок на авто.",
    description_ru:
      "Комплект Cybex Mios 3 в 1 добавляет к фирменной лёгкой раме автокресло группы 0+ с системой крепления без базы. Это решение для семей, которым нужна одна коляска на все случаи — от роддома до поездок на авто.",
    brand: "Cybex",
    category_slug: "strollers-3in1",
    price: 64000,
    old_price: null,
    stock_status: "out_of_stock",
    specs: strollerSpecs("12.4 кг", "0–4 роки (з автокріслом)", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Balios S Lux (прогулянкова) ---
  {
    slug: "cybex-balios-s-cozy-beige",
    name_ua: "Коляска Cybex Balios S Lux (Cozy Beige)",
    name_ru: "Коляска Cybex Balios S Lux (Cozy Beige)",
    description_ua:
      "Cybex Balios S Lux — прогулянкова коляска з великим капюшоном UV 50+ та плавним ходом на надувних колесах. Знімний бампер, глибокий відкидний козирок і зручний кошик роблять її практичним вибором для щоденних прогулянок.",
    description_ru:
      "Cybex Balios S Lux — прогулочная коляска с большим капюшоном UV 50+ и плавным ходом на надувных колёсах. Съёмный бампер, глубокий откидной козырёк и вместительная корзина делают её практичным выбором для ежедневных прогулок.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 29000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.4 кг", "6 міс – 4 роки", "компактне", "надувні"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "cybex-balios-s-lava-red",
    name_ua: "Коляска Cybex Balios S Lux (Lava Red)",
    name_ru: "Коляска Cybex Balios S Lux (Lava Red)",
    description_ua:
      "Cybex Balios S Lux — прогулянкова коляска з великим капюшоном UV 50+ та плавним ходом на надувних колесах. Знімний бампер, глибокий відкидний козирок і зручний кошик роблять її практичним вибором для щоденних прогулянок.",
    description_ru:
      "Cybex Balios S Lux — прогулочная коляска с большим капюшоном UV 50+ и плавным ходом на надувных колёсах. Съёмный бампер, глубокий откидной козырёк и вместительная корзина делают её практичным выбором для ежедневных прогулок.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 29000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.4 кг", "6 міс – 4 роки", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-balios-s-soho-grey",
    name_ua: "Коляска Cybex Balios S Lux (Soho Grey)",
    name_ru: "Коляска Cybex Balios S Lux (Soho Grey)",
    description_ua:
      "Cybex Balios S Lux — прогулянкова коляска з великим капюшоном UV 50+ та плавним ходом на надувних колесах. Знімний бампер, глибокий відкидний козирок і зручний кошик роблять її практичним вибором для щоденних прогулянок.",
    description_ru:
      "Cybex Balios S Lux — прогулочная коляска с большим капюшоном UV 50+ и плавным ходом на надувных колёсах. Съёмный бампер, глубокий откидной козырёк и вместительная корзина делают её практичным выбором для ежедневных прогулок.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 29500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.4 кг", "6 міс – 4 роки", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-balios-s-deep-black",
    name_ua: "Коляска Cybex Balios S Lux (Deep Black)",
    name_ru: "Коляска Cybex Balios S Lux (Deep Black)",
    description_ua:
      "Cybex Balios S Lux — прогулянкова коляска з великим капюшоном UV 50+ та плавним ходом на надувних колесах. Знімний бампер, глибокий відкидний козирок і зручний кошик роблять її практичним вибором для щоденних прогулянок.",
    description_ru:
      "Cybex Balios S Lux — прогулочная коляска с большим капюшоном UV 50+ и плавным ходом на надувных колёсах. Съёмный бампер, глубокий откидной козырёк и вместительная корзина делают её практичным выбором для ежедневных прогулок.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 30000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("10.4 кг", "6 міс – 4 роки", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-balios-s-sepia-black",
    name_ua: "Коляска Cybex Balios S Lux (Sepia Black)",
    name_ru: "Коляска Cybex Balios S Lux (Sepia Black)",
    description_ua:
      "Cybex Balios S Lux — прогулянкова коляска з великим капюшоном UV 50+ та плавним ходом на надувних колесах. Знімний бампер, глибокий відкидний козирок і зручний кошик роблять її практичним вибором для щоденних прогулянок.",
    description_ru:
      "Cybex Balios S Lux — прогулочная коляска с большим капюшоном UV 50+ и плавным ходом на надувных колёсах. Съёмный бампер, глубокий откидной козырёк и вместительная корзина делают её практичным выбором для ежедневных прогулок.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 30000,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("10.4 кг", "6 міс – 4 роки", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Talos S Lux (прогулянкова, для бездоріжжя) ---
  {
    slug: "cybex-talos-s-lava-red",
    name_ua: "Коляска Cybex Talos S Lux (Lava Red)",
    name_ru: "Коляска Cybex Talos S Lux (Lava Red)",
    description_ua:
      "Cybex Talos S Lux створений для активних прогулянок бездоріжжям: посилена підвіска та колеса більшого діаметра впевнено долають ґрунтові стежки і бруківку. Регульована в декількох положеннях спинка та розширений капюшон додають комфорту в будь-яку погоду.",
    description_ru:
      "Cybex Talos S Lux создан для активных прогулок по бездорожью: усиленная подвеска и колёса большего диаметра уверенно преодолевают грунтовые тропинки и брусчатку. Регулируемая в нескольких положениях спинка и расширенный капюшон добавляют комфорта в любую погоду.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 34000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("11.2 кг", "6 міс – 4 роки", "компактне", "надувні посилені"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-talos-s-soho-grey",
    name_ua: "Коляска Cybex Talos S Lux (Soho Grey)",
    name_ru: "Коляска Cybex Talos S Lux (Soho Grey)",
    description_ua:
      "Cybex Talos S Lux створений для активних прогулянок бездоріжжям: посилена підвіска та колеса більшого діаметра впевнено долають ґрунтові стежки і бруківку. Регульована в декількох положеннях спинка та розширений капюшон додають комфорту в будь-яку погоду.",
    description_ru:
      "Cybex Talos S Lux создан для активных прогулок по бездорожью: усиленная подвеска и колёса большего диаметра уверенно преодолевают грунтовые тропинки и брусчатку. Регулируемая в нескольких положениях спинка и расширенный капюшон добавляют комфорта в любую погоду.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 34000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("11.2 кг", "6 міс – 4 роки", "компактне", "надувні посилені"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-talos-s-moon-black",
    name_ua: "Коляска Cybex Talos S Lux (Moon Black)",
    name_ru: "Коляска Cybex Talos S Lux (Moon Black)",
    description_ua:
      "Cybex Talos S Lux створений для активних прогулянок бездоріжжям: посилена підвіска та колеса більшого діаметра впевнено долають ґрунтові стежки і бруківку. Регульована в декількох положеннях спинка та розширений капюшон додають комфорту в будь-яку погоду.",
    description_ru:
      "Cybex Talos S Lux создан для активных прогулок по бездорожью: усиленная подвеска и колёса большего диаметра уверенно преодолевают грунтовые тропинки и брусчатку. Регулируемая в нескольких положениях спинка и расширенный капюшон добавляют комфорта в любую погоду.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 34500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("11.2 кг", "6 міс – 4 роки", "компактне", "надувні посилені"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-talos-s-khaki-green",
    name_ua: "Коляска Cybex Talos S Lux (Khaki Green)",
    name_ru: "Коляска Cybex Talos S Lux (Khaki Green)",
    description_ua:
      "Cybex Talos S Lux створений для активних прогулянок бездоріжжям: посилена підвіска та колеса більшого діаметра впевнено долають ґрунтові стежки і бруківку. Регульована в декількох положеннях спинка та розширений капюшон додають комфорту в будь-яку погоду.",
    description_ru:
      "Cybex Talos S Lux создан для активных прогулок по бездорожью: усиленная подвеска и колёса большего диаметра уверенно преодолевают грунтовые тропинки и брусчатку. Регулируемая в нескольких положениях спинка и расширенный капюшон добавляют комфорта в любую погоду.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 35000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("11.2 кг", "6 міс – 4 роки", "компактне", "надувні посилені"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "cybex-talos-s-cozy-beige",
    name_ua: "Коляска Cybex Talos S Lux (Cozy Beige)",
    name_ru: "Коляска Cybex Talos S Lux (Cozy Beige)",
    description_ua:
      "Cybex Talos S Lux створений для активних прогулянок бездоріжжям: посилена підвіска та колеса більшого діаметра впевнено долають ґрунтові стежки і бруківку. Регульована в декількох положеннях спинка та розширений капюшон додають комфорту в будь-яку погоду.",
    description_ru:
      "Cybex Talos S Lux создан для активных прогулок по бездорожью: усиленная подвеска и колёса большего диаметра уверенно преодолевают грунтовые тропинки и брусчатку. Регулируемая в нескольких положениях спинка и расширенный капюшон добавляют комфорта в любую погоду.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 34000,
    old_price: 38000,
    stock_status: "in_stock",
    specs: strollerSpecs("11.2 кг", "6 міс – 4 роки", "компактне", "надувні посилені"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  // --- Eezy S Twist+2 (прогулянкова) ---
  {
    slug: "cybex-eezy-s-twist2-cashmere-beige",
    name_ua: "Коляска Cybex Eezy S Twist+2 (Cashmere Beige)",
    name_ru: "Коляска Cybex Eezy S Twist+2 (Cashmere Beige)",
    description_ua:
      "Cybex Eezy S Twist+2 має унікальне сидіння, що обертається на 360°, — дитину можна розвернути обличчям до мами без розвороту всієї коляски. Складається компактно однією рукою і підходить для подорожей у ручній поклажі.",
    description_ru:
      "Cybex Eezy S Twist+2 оснащена уникальным сиденьем с поворотом на 360° — ребёнка можно развернуть лицом к маме без разворота всей коляски. Складывается компактно одной рукой и подходит для поездок в ручной клади.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 23000,
    old_price: 26000,
    stock_status: "in_stock",
    specs: strollerSpecs("9.7 кг", "0–3.5 років", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "cybex-eezy-s-twist2-moon-black",
    name_ua: "Коляска Cybex Eezy S Twist+2 (Moon Black)",
    name_ru: "Коляска Cybex Eezy S Twist+2 (Moon Black)",
    description_ua:
      "Cybex Eezy S Twist+2 має унікальне сидіння, що обертається на 360°, — дитину можна розвернути обличчям до мами без розвороту всієї коляски. Складається компактно однією рукою і підходить для подорожей у ручній поклажі.",
    description_ru:
      "Cybex Eezy S Twist+2 оснащена уникальным сиденьем с поворотом на 360° — ребёнка можно развернуть лицом к маме без разворота всей коляски. Складывается компактно одной рукой и подходит для поездок в ручной клади.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 26000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("9.7 кг", "0–3.5 років", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-eezy-s-twist2-lava-red",
    name_ua: "Коляска Cybex Eezy S Twist+2 (Lava Red)",
    name_ru: "Коляска Cybex Eezy S Twist+2 (Lava Red)",
    description_ua:
      "Cybex Eezy S Twist+2 має унікальне сидіння, що обертається на 360°, — дитину можна розвернути обличчям до мами без розвороту всієї коляски. Складається компактно однією рукою і підходить для подорожей у ручній поклажі.",
    description_ru:
      "Cybex Eezy S Twist+2 оснащена уникальным сиденьем с поворотом на 360° — ребёнка можно развернуть лицом к маме без разворота всей коляски. Складывается компактно одной рукой и подходит для поездок в ручной клади.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 26000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("9.7 кг", "0–3.5 років", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-eezy-s-twist2-soho-grey",
    name_ua: "Коляска Cybex Eezy S Twist+2 (Soho Grey)",
    name_ru: "Коляска Cybex Eezy S Twist+2 (Soho Grey)",
    description_ua:
      "Cybex Eezy S Twist+2 має унікальне сидіння, що обертається на 360°, — дитину можна розвернути обличчям до мами без розвороту всієї коляски. Складається компактно однією рукою і підходить для подорожей у ручній поклажі.",
    description_ru:
      "Cybex Eezy S Twist+2 оснащена уникальным сиденьем с поворотом на 360° — ребёнка можно развернуть лицом к маме без разворота всей коляски. Складывается компактно одной рукой и подходит для поездок в ручной клади.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 26500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("9.7 кг", "0–3.5 років", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-eezy-s-twist2-sepia-black",
    name_ua: "Коляска Cybex Eezy S Twist+2 (Sepia Black)",
    name_ru: "Коляска Cybex Eezy S Twist+2 (Sepia Black)",
    description_ua:
      "Cybex Eezy S Twist+2 має унікальне сидіння, що обертається на 360°, — дитину можна розвернути обличчям до мами без розвороту всієї коляски. Складається компактно однією рукою і підходить для подорожей у ручній поклажі.",
    description_ru:
      "Cybex Eezy S Twist+2 оснащена уникальным сиденьем с поворотом на 360° — ребёнка можно развернуть лицом к маме без разворота всей коляски. Складывается компактно одной рукой и подходит для поездок в ручной клади.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 27000,
    old_price: null,
    stock_status: "out_of_stock",
    specs: strollerSpecs("9.7 кг", "0–3.5 років", "компактне одним рухом", "гумові надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Beezy (ультракомпактна прогулянкова) ---
  {
    slug: "cybex-beezy-moon-black",
    name_ua: "Коляска Cybex Beezy (Moon Black)",
    name_ru: "Коляска Cybex Beezy (Moon Black)",
    description_ua:
      "Cybex Beezy — наймініатюрніша прогулянкова коляска бренду, яка складається одним рухом у пакет розміром з парасольку і важить менше 7 кг. Ремінець для перенесення на плечі робить її зручним супутником у подорожах літаком.",
    description_ru:
      "Cybex Beezy — самая миниатюрная прогулочная коляска бренда, которая складывается одним движением в пакет размером с зонт и весит меньше 7 кг. Ремешок для переноски на плече делает её удобным спутником в путешествиях самолётом.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 20000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("6.9 кг", "6 міс – 3.5 років", "парасолька одним рухом", "поліуретанові"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "cybex-beezy-lava-red",
    name_ua: "Коляска Cybex Beezy (Lava Red)",
    name_ru: "Коляска Cybex Beezy (Lava Red)",
    description_ua:
      "Cybex Beezy — наймініатюрніша прогулянкова коляска бренду, яка складається одним рухом у пакет розміром з парасольку і важить менше 7 кг. Ремінець для перенесення на плечі робить її зручним супутником у подорожах літаком.",
    description_ru:
      "Cybex Beezy — самая миниатюрная прогулочная коляска бренда, которая складывается одним движением в пакет размером с зонт и весит меньше 7 кг. Ремешок для переноски на плече делает её удобным спутником в путешествиях самолётом.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 20000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("6.9 кг", "6 міс – 3.5 років", "парасолька одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-beezy-soho-grey",
    name_ua: "Коляска Cybex Beezy (Soho Grey)",
    name_ru: "Коляска Cybex Beezy (Soho Grey)",
    description_ua:
      "Cybex Beezy — наймініатюрніша прогулянкова коляска бренду, яка складається одним рухом у пакет розміром з парасольку і важить менше 7 кг. Ремінець для перенесення на плечі робить її зручним супутником у подорожах літаком.",
    description_ru:
      "Cybex Beezy — самая миниатюрная прогулочная коляска бренда, которая складывается одним движением в пакет размером с зонт и весит меньше 7 кг. Ремешок для переноски на плече делает её удобным спутником в путешествиях самолётом.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 20500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("6.9 кг", "6 міс – 3.5 років", "парасолька одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Orfeo (2в1, компактна міська) ---
  {
    slug: "cybex-orfeo-urban-black",
    name_ua: "Коляска Cybex Orfeo 2 в 1 (Urban Black)",
    name_ru: "Коляска Cybex Orfeo 2 в 1 (Urban Black)",
    description_ua:
      "Cybex Orfeo поєднує пружну люльку для перших місяців життя з легким прогулянковим блоком в одному компактному шасі. Обертове переднє колесо та м'яка амортизація тримають хід плавним навіть на нерівному тротуарі.",
    description_ru:
      "Cybex Orfeo сочетает пружинистую люльку для первых месяцев жизни с лёгким прогулочным блоком в одном компактном шасси. Поворотное переднее колесо и мягкая амортизация держат ход плавным даже на неровном тротуаре.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 50000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("9.9 кг", "0–3 роки", "компактне одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-orfeo-classic-beige",
    name_ua: "Коляска Cybex Orfeo 2 в 1 (Classic Beige)",
    name_ru: "Коляска Cybex Orfeo 2 в 1 (Classic Beige)",
    description_ua:
      "Cybex Orfeo поєднує пружну люльку для перших місяців життя з легким прогулянковим блоком в одному компактному шасі. Обертове переднє колесо та м'яка амортизація тримають хід плавним навіть на нерівному тротуарі.",
    description_ru:
      "Cybex Orfeo сочетает пружинистую люльку для первых месяцев жизни с лёгким прогулочным блоком в одном компактном шасси. Поворотное переднее колесо и мягкая амортизация держат ход плавным даже на неровном тротуаре.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 51000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("9.9 кг", "0–3 роки", "компактне одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-orfeo-soho-grey",
    name_ua: "Коляска Cybex Orfeo 2 в 1 (Soho Grey)",
    name_ru: "Коляска Cybex Orfeo 2 в 1 (Soho Grey)",
    description_ua:
      "Cybex Orfeo поєднує пружну люльку для перших місяців життя з легким прогулянковим блоком в одному компактному шасі. Обертове переднє колесо та м'яка амортизація тримають хід плавним навіть на нерівному тротуарі.",
    description_ru:
      "Cybex Orfeo сочетает пружинистую люльку для первых месяцев жизни с лёгким прогулочным блоком в одном компактном шасси. Поворотное переднее колесо и мягкая амортизация держат ход плавным даже на неровном тротуаре.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 51000,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("9.9 кг", "0–3 роки", "компактне одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Libelle (прогулянкова, ультракомпактна) ---
  {
    slug: "cybex-libelle-moon-black",
    name_ua: "Коляска Cybex Libelle (Moon Black)",
    name_ru: "Коляска Cybex Libelle (Moon Black)",
    description_ua:
      "Cybex Libelle — ультракомпактна коляска, яка складається одним рухом і стоїть самостійно у складеному вигляді, а розмір дозволяє класти її на верхню полицю в літаку. При цьому спинка відкидається у майже горизонтальне положення для сну.",
    description_ru:
      "Cybex Libelle — ультракомпактная коляска, которая складывается одним движением и стоит самостоятельно в сложенном виде, а размер позволяет класть её на верхнюю полку в самолёте. При этом спинка откидывается в почти горизонтальное положение для сна.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 30000,
    old_price: 34000,
    stock_status: "in_stock",
    specs: strollerSpecs("7.3 кг", "6 міс – 4 роки", "одним рухом, стоїть складена", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "cybex-libelle-lava-red",
    name_ua: "Коляска Cybex Libelle (Lava Red)",
    name_ru: "Коляска Cybex Libelle (Lava Red)",
    description_ua:
      "Cybex Libelle — ультракомпактна коляска, яка складається одним рухом і стоїть самостійно у складеному вигляді, а розмір дозволяє класти її на верхню полицю в літаку. При цьому спинка відкидається у майже горизонтальне положення для сну.",
    description_ru:
      "Cybex Libelle — ультракомпактная коляска, которая складывается одним движением и стоит самостоятельно в сложенном виде, а размер позволяет класть её на верхнюю полку в самолёте. При этом спинка откидывается в почти горизонтальное положение для сна.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 34000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.3 кг", "6 міс – 4 роки", "одним рухом, стоїть складена", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-libelle-cozy-beige",
    name_ua: "Коляска Cybex Libelle (Cozy Beige)",
    name_ru: "Коляска Cybex Libelle (Cozy Beige)",
    description_ua:
      "Cybex Libelle — ультракомпактна коляска, яка складається одним рухом і стоїть самостійно у складеному вигляді, а розмір дозволяє класти її на верхню полицю в літаку. При цьому спинка відкидається у майже горизонтальне положення для сну.",
    description_ru:
      "Cybex Libelle — ультракомпактная коляска, которая складывается одним движением и стоит самостоятельно в сложенном виде, а размер позволяет класть её на верхнюю полку в самолёте. При этом спинка откидывается в почти горизонтальное положение для сна.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 34500,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.3 кг", "6 міс – 4 роки", "одним рухом, стоїть складена", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-libelle-soho-grey",
    name_ua: "Коляска Cybex Libelle (Soho Grey)",
    name_ru: "Коляска Cybex Libelle (Soho Grey)",
    description_ua:
      "Cybex Libelle — ультракомпактна коляска, яка складається одним рухом і стоїть самостійно у складеному вигляді, а розмір дозволяє класти її на верхню полицю в літаку. При цьому спинка відкидається у майже горизонтальне положення для сну.",
    description_ru:
      "Cybex Libelle — ультракомпактная коляска, которая складывается одним движением и стоит самостоятельно в сложенном виде, а размер позволяет класть её на верхнюю полку в самолёте. При этом спинка откидывается в почти горизонтальное положение для сна.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 35000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("7.3 кг", "6 міс – 4 роки", "одним рухом, стоїть складена", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Coya (прогулянкова, преміум) ---
  {
    slug: "cybex-coya-seashell-beige",
    name_ua: "Коляска Cybex Coya (Seashell Beige)",
    name_ru: "Коляска Cybex Coya (Seashell Beige)",
    description_ua:
      "Cybex Coya поєднує компактність міської коляски з преміальним оздобленням: шкіряна ручка, матова рама та обʼємний капюшон із виходом для сонця. Підходить від народження завдяки глибокому відкиданню спинки в горизонт.",
    description_ru:
      "Cybex Coya сочетает компактность городской коляски с премиальной отделкой: кожаная ручка, матовая рама и объёмный капюшон с окном для солнца. Подходит с рождения благодаря глубокому откидыванию спинки в горизонт.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 45000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.9 кг", "0–4 роки", "компактне одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-coya-sepia-black",
    name_ua: "Коляска Cybex Coya (Sepia Black)",
    name_ru: "Коляска Cybex Coya (Sepia Black)",
    description_ua:
      "Cybex Coya поєднує компактність міської коляски з преміальним оздобленням: шкіряна ручка, матова рама та обʼємний капюшон із виходом для сонця. Підходить від народження завдяки глибокому відкиданню спинки в горизонт.",
    description_ru:
      "Cybex Coya сочетает компактность городской коляски с премиальной отделкой: кожаная ручка, матовая рама и объёмный капюшон с окном для солнца. Подходит с рождения благодаря глубокому откидыванию спинки в горизонт.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 46000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.9 кг", "0–4 роки", "компактне одним рухом", "поліуретанові"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "cybex-coya-manhattan-grey",
    name_ua: "Коляска Cybex Coya (Manhattan Grey)",
    name_ru: "Коляска Cybex Coya (Manhattan Grey)",
    description_ua:
      "Cybex Coya поєднує компактність міської коляски з преміальним оздобленням: шкіряна ручка, матова рама та обʼємний капюшон із виходом для сонця. Підходить від народження завдяки глибокому відкиданню спинки в горизонт.",
    description_ru:
      "Cybex Coya сочетает компактность городской коляски с премиальной отделкой: кожаная ручка, матовая рама и объёмный капюшон с окном для солнца. Подходит с рождения благодаря глубокому откидыванию спинки в горизонт.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 46000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("8.9 кг", "0–4 роки", "компактне одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-coya-nude-beige",
    name_ua: "Коляска Cybex Coya (Nude Beige)",
    name_ru: "Коляска Cybex Coya (Nude Beige)",
    description_ua:
      "Cybex Coya поєднує компактність міської коляски з преміальним оздобленням: шкіряна ручка, матова рама та обʼємний капюшон із виходом для сонця. Підходить від народження завдяки глибокому відкиданню спинки в горизонт.",
    description_ru:
      "Cybex Coya сочетает компактность городской коляски с премиальной отделкой: кожаная ручка, матовая рама и объёмный капюшон с окном для солнца. Подходит с рождения благодаря глубокому откидыванию спинки в горизонт.",
    brand: "Cybex",
    category_slug: "strollers-buggy",
    price: 47000,
    old_price: 53000,
    stock_status: "in_stock",
    specs: strollerSpecs("8.9 кг", "0–4 роки", "компактне одним рухом", "поліуретанові"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  // --- Gazelle S (одномісна, кандидат для двійні через комплект Duo) ---
  {
    slug: "cybex-gazelle-s-lava-red",
    name_ua: "Коляска Cybex Gazelle S (Lava Red)",
    name_ru: "Коляска Cybex Gazelle S (Lava Red)",
    description_ua:
      "Cybex Gazelle S — коляска-платформа з ремінцевою підвіскою замість традиційних амортизаторів, що дає особливо м'який хід по будь-якій поверхні. Сидіння встановлюється обличчям до батьків або від них, а за потреби шасі приймає друге сидіння для двійні чи погодок.",
    description_ru:
      "Cybex Gazelle S — коляска-платформа с ремённой подвеской вместо традиционных амортизаторов, что даёт особенно мягкий ход по любой поверхности. Сиденье устанавливается лицом к родителям или от них, а при необходимости шасси принимает второе сиденье для двойни или погодок.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 48000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.8 кг", "0–4 роки", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-gazelle-s-soho-grey",
    name_ua: "Коляска Cybex Gazelle S (Soho Grey)",
    name_ru: "Коляска Cybex Gazelle S (Soho Grey)",
    description_ua:
      "Cybex Gazelle S — коляска-платформа з ремінцевою підвіскою замість традиційних амортизаторів, що дає особливо м'який хід по будь-якій поверхні. Сидіння встановлюється обличчям до батьків або від них, а за потреби шасі приймає друге сидіння для двійні чи погодок.",
    description_ru:
      "Cybex Gazelle S — коляска-платформа с ремённой подвеской вместо традиционных амортизаторов, что даёт особенно мягкий ход по любой поверхности. Сиденье устанавливается лицом к родителям или от них, а при необходимости шасси принимает второе сиденье для двойни или погодок.",
    brand: "Cybex",
    category_slug: "strollers-2in1",
    price: 48000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("13.8 кг", "0–4 роки", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Gazelle S Duo (комплект для двійні / погодок) ---
  {
    slug: "cybex-gazelle-s-duo-moon-black",
    name_ua: "Коляска для двійні Cybex Gazelle S Duo (Moon Black)",
    name_ru: "Коляска для двойни Cybex Gazelle S Duo (Moon Black)",
    description_ua:
      "Комплект Cybex Gazelle S Duo додає до фірмової платформи Gazelle S друге сидіння, перетворюючи одномісну коляску на повноцінну для двійні чи дітей погодок. Обидва сидіння незалежно регулюються по нахилу і можуть дивитися в різні боки.",
    description_ru:
      "Комплект Cybex Gazelle S Duo добавляет к фирменной платформе Gazelle S второе сиденье, превращая одноместную коляску в полноценную для двойни или погодок. Оба сиденья независимо регулируются по наклону и могут смотреть в разные стороны.",
    brand: "Cybex",
    category_slug: "strollers-twins",
    price: 68000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("16.4 кг", "0–4 роки (двоє дітей)", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-gazelle-s-duo-soho-grey",
    name_ua: "Коляска для двійні Cybex Gazelle S Duo (Soho Grey)",
    name_ru: "Коляска для двойни Cybex Gazelle S Duo (Soho Grey)",
    description_ua:
      "Комплект Cybex Gazelle S Duo додає до фірмової платформи Gazelle S друге сидіння, перетворюючи одномісну коляску на повноцінну для двійні чи дітей погодок. Обидва сидіння незалежно регулюються по нахилу і можуть дивитися в різні боки.",
    description_ru:
      "Комплект Cybex Gazelle S Duo добавляет к фирменной платформе Gazelle S второе сиденье, превращая одноместную коляску в полноценную для двойни или погодок. Оба сиденья независимо регулируются по наклону и могут смотреть в разные стороны.",
    brand: "Cybex",
    category_slug: "strollers-twins",
    price: 68000,
    old_price: null,
    stock_status: "preorder",
    specs: strollerSpecs("16.4 кг", "0–4 роки (двоє дітей)", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-gazelle-s-duo-lux-lava-red",
    name_ua: "Коляска для двійні Cybex Gazelle S Duo Lux (Lava Red)",
    name_ru: "Коляска для двойни Cybex Gazelle S Duo Lux (Lava Red)",
    description_ua:
      "Версія Lux комплекту Gazelle S Duo додає шкіряну ручку та преміальну тканину сидінь, зберігаючи фірмову ремінцеву підвіску для двох дітей одночасно. Кожне сидіння складається окремо, якщо друга дитина підросла і пересіла на самокат.",
    description_ru:
      "Версия Lux комплекта Gazelle S Duo добавляет кожаную ручку и премиальную ткань сидений, сохраняя фирменную ремённую подвеску для двух детей одновременно. Каждое сиденье складывается отдельно, если второй ребёнок подрос и пересел на самокат.",
    brand: "Cybex",
    category_slug: "strollers-twins",
    price: 72000,
    old_price: null,
    stock_status: "in_stock",
    specs: strollerSpecs("16.7 кг", "0–4 роки (двоє дітей)", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-gazelle-s-duo-lux-cozy-beige",
    name_ua: "Коляска для двійні Cybex Gazelle S Duo Lux (Cozy Beige)",
    name_ru: "Коляска для двойни Cybex Gazelle S Duo Lux (Cozy Beige)",
    description_ua:
      "Версія Lux комплекту Gazelle S Duo додає шкіряну ручку та преміальну тканину сидінь, зберігаючи фірмову ремінцеву підвіску для двох дітей одночасно. Кожне сидіння складається окремо, якщо друга дитина підросла і пересіла на самокат.",
    description_ru:
      "Версия Lux комплекта Gazelle S Duo добавляет кожаную ручку и премиальную ткань сидений, сохраняя фирменную ремённую подвеску для двух детей одновременно. Каждое сиденье складывается отдельно, если второй ребёнок подрос и пересел на самокат.",
    brand: "Cybex",
    category_slug: "strollers-twins",
    price: 72000,
    old_price: 80000,
    stock_status: "in_stock",
    specs: strollerSpecs("16.7 кг", "0–4 роки (двоє дітей)", "компактне", "надувні"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  // --- Aton B2 (автокрісло 0+) ---
  {
    slug: "cybex-aton-b2-lava-red",
    name_ua: "Автокрісло Cybex Aton B2 (Lava Red)",
    name_ru: "Автокресло Cybex Aton B2 (Lava Red)",
    description_ua:
      "Cybex Aton B2 — легке автокрісло групи 0+ для перших поїздок немовляти, сумісне з більшістю шасі колясок Cybex та Anex через фірмові адаптери. Лінійний поглинач удару в зоні голови підвищує захист при бічному зіткненні.",
    description_ru:
      "Cybex Aton B2 — лёгкое автокресло группы 0+ для первых поездок младенца, совместимое с большинством шасси колясок Cybex и Anex через фирменные адаптеры. Линейный амортизатор удара в зоне головы повышает защиту при боковом столкновении.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 21000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("3.6 кг", "0+ (до 13 кг)", "ремені авто / адаптери на коляску", "45–76 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-aton-b2-sepia-black",
    name_ua: "Автокрісло Cybex Aton B2 (Sepia Black)",
    name_ru: "Автокресло Cybex Aton B2 (Sepia Black)",
    description_ua:
      "Cybex Aton B2 — легке автокрісло групи 0+ для перших поїздок немовляти, сумісне з більшістю шасі колясок Cybex та Anex через фірмові адаптери. Лінійний поглинач удару в зоні голови підвищує захист при бічному зіткненні.",
    description_ru:
      "Cybex Aton B2 — лёгкое автокресло группы 0+ для первых поездок младенца, совместимое с большинством шасси колясок Cybex и Anex через фирменные адаптеры. Линейный амортизатор удара в зоне головы повышает защиту при боковом столкновении.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 21500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("3.6 кг", "0+ (до 13 кг)", "ремені авто / адаптери на коляску", "45–76 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-aton-b2-soho-grey",
    name_ua: "Автокрісло Cybex Aton B2 (Soho Grey)",
    name_ru: "Автокресло Cybex Aton B2 (Soho Grey)",
    description_ua:
      "Cybex Aton B2 — легке автокрісло групи 0+ для перших поїздок немовляти, сумісне з більшістю шасі колясок Cybex та Anex через фірмові адаптери. Лінійний поглинач удару в зоні голови підвищує захист при бічному зіткненні.",
    description_ru:
      "Cybex Aton B2 — лёгкое автокресло группы 0+ для первых поездок младенца, совместимое с большинством шасси колясок Cybex и Anex через фирменные адаптеры. Линейный амортизатор удара в зоне головы повышает защиту при боковом столкновении.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 21500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("3.6 кг", "0+ (до 13 кг)", "ремені авто / адаптери на коляску", "45–76 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Aton S2 i-Size (автокрісло 0+) ---
  {
    slug: "cybex-aton-s2-isize-lava-red",
    name_ua: "Автокрісло Cybex Aton S2 i-Size (Lava Red)",
    name_ru: "Автокресло Cybex Aton S2 i-Size (Lava Red)",
    description_ua:
      "Cybex Aton S2 i-Size — оновлена версія бестселера Aton з опорною ніжкою для встановлення на базу i-Size без ISOFIX-кріплень в авто. Лінійний поглинач удару та глибокий каркас з піни захищають голову немовляти при боковому ударі.",
    description_ru:
      "Cybex Aton S2 i-Size — обновлённая версия бестселлера Aton с опорной ногой для установки на базу i-Size без ISOFIX-креплений в авто. Линейный амортизатор удара и глубокий каркас из пены защищают голову младенца при боковом ударе.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 24000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("4.1 кг", "0+ (до 87 см)", "база i-Size + опорна ніжка", "45–87 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-aton-s2-isize-moon-black",
    name_ua: "Автокрісло Cybex Aton S2 i-Size (Moon Black)",
    name_ru: "Автокресло Cybex Aton S2 i-Size (Moon Black)",
    description_ua:
      "Cybex Aton S2 i-Size — оновлена версія бестселера Aton з опорною ніжкою для встановлення на базу i-Size без ISOFIX-кріплень в авто. Лінійний поглинач удару та глибокий каркас з піни захищають голову немовляти при боковому ударі.",
    description_ru:
      "Cybex Aton S2 i-Size — обновлённая версия бестселлера Aton с опорной ногой для установки на базу i-Size без ISOFIX-креплений в авто. Линейный амортизатор удара и глубокий каркас из пены защищают голову младенца при боковом ударе.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 24500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("4.1 кг", "0+ (до 87 см)", "база i-Size + опорна ніжка", "45–87 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-aton-s2-isize-soho-grey",
    name_ua: "Автокрісло Cybex Aton S2 i-Size (Soho Grey)",
    name_ru: "Автокресло Cybex Aton S2 i-Size (Soho Grey)",
    description_ua:
      "Cybex Aton S2 i-Size — оновлена версія бестселера Aton з опорною ніжкою для встановлення на базу i-Size без ISOFIX-кріплень в авто. Лінійний поглинач удару та глибокий каркас з піни захищають голову немовляти при боковому ударі.",
    description_ru:
      "Cybex Aton S2 i-Size — обновлённая версия бестселлера Aton с опорной ногой для установки на базу i-Size без ISOFIX-креплений в авто. Линейный амортизатор удара и глубокий каркас из пены защищают голову младенца при боковом ударе.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 24500,
    old_price: null,
    stock_status: "preorder",
    specs: carSeatSpecs("4.1 кг", "0+ (до 87 см)", "база i-Size + опорна ніжка", "45–87 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Cloud T i-Size (автокрісло-люлька) ---
  {
    slug: "cybex-cloud-t-isize-sepia-black",
    name_ua: "Автокрісло Cybex Cloud T i-Size (Sepia Black)",
    name_ru: "Автокресло Cybex Cloud T i-Size (Sepia Black)",
    description_ua:
      "Cybex Cloud T i-Size — автокрісло-люлька для найменших з поворотом на 360° та вбудованим лінійним поглиначем удару. Встановлюється лише на базу ISOFIX, а функція гойдання заспокоює малюка навіть у припаркованому авто.",
    description_ru:
      "Cybex Cloud T i-Size — автокресло-люлька для самых маленьких с поворотом на 360° и встроенным линейным амортизатором удара. Устанавливается только на базу ISOFIX, а функция укачивания успокаивает малыша даже в припаркованном авто.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 33000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("6.4 кг", "0+ (до 87 см)", "ISOFIX (лише з базою)", "45–87 см"),
    images: [],
    is_hit: true,
    is_sale: false,
  },
  {
    slug: "cybex-cloud-t-isize-seashell-beige",
    name_ua: "Автокрісло Cybex Cloud T i-Size (Seashell Beige)",
    name_ru: "Автокресло Cybex Cloud T i-Size (Seashell Beige)",
    description_ua:
      "Cybex Cloud T i-Size — автокрісло-люлька для найменших з поворотом на 360° та вбудованим лінійним поглиначем удару. Встановлюється лише на базу ISOFIX, а функція гойдання заспокоює малюка навіть у припаркованому авто.",
    description_ru:
      "Cybex Cloud T i-Size — автокресло-люлька для самых маленьких с поворотом на 360° и встроенным линейным амортизатором удара. Устанавливается только на базу ISOFIX, а функция укачивания успокаивает малыша даже в припаркованном авто.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 33000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("6.4 кг", "0+ (до 87 см)", "ISOFIX (лише з базою)", "45–87 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-cloud-t-isize-plum",
    name_ua: "Автокрісло Cybex Cloud T i-Size (Plum)",
    name_ru: "Автокресло Cybex Cloud T i-Size (Plum)",
    description_ua:
      "Cybex Cloud T i-Size — автокрісло-люлька для найменших з поворотом на 360° та вбудованим лінійним поглиначем удару. Встановлюється лише на базу ISOFIX, а функція гойдання заспокоює малюка навіть у припаркованому авто.",
    description_ru:
      "Cybex Cloud T i-Size — автокресло-люлька для самых маленьких с поворотом на 360° и встроенным линейным амортизатором удара. Устанавливается только на базу ISOFIX, а функция укачивания успокаивает малыша даже в припаркованном авто.",
    brand: "Cybex",
    category_slug: "car-seats-0plus",
    price: 34000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("6.4 кг", "0+ (до 87 см)", "ISOFIX (лише з базою)", "45–87 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Sirona T i-Size (автокрісло, обертове) ---
  {
    slug: "cybex-sirona-t-isize-plum",
    name_ua: "Автокрісло Cybex Sirona T i-Size (Plum)",
    name_ru: "Автокресло Cybex Sirona T i-Size (Plum)",
    description_ua:
      "Cybex Sirona T i-Size росте разом із дитиною від народження до 4 років і обертається на 360° для зручного саджання без нахилу над салоном. Проти-ротаційна опора та бокова система захисту забезпечують додаткову безпеку при боковому ударі.",
    description_ru:
      "Cybex Sirona T i-Size растёт вместе с ребёнком от рождения до 4 лет и поворачивается на 360° для удобной посадки без наклона над салоном. Противоротационная опора и боковая система защиты обеспечивают дополнительную безопасность при боковом ударе.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 41000,
    old_price: 46000,
    stock_status: "in_stock",
    specs: carSeatSpecs("13.5 кг", "0+/I/II (до 105 см)", "ISOFIX + опора", "45–105 см"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  {
    slug: "cybex-sirona-t-isize-graphite-black",
    name_ua: "Автокрісло Cybex Sirona T i-Size (Graphite Black)",
    name_ru: "Автокресло Cybex Sirona T i-Size (Graphite Black)",
    description_ua:
      "Cybex Sirona T i-Size росте разом із дитиною від народження до 4 років і обертається на 360° для зручного саджання без нахилу над салоном. Проти-ротаційна опора та бокова система захисту забезпечують додаткову безпеку при боковому ударі.",
    description_ru:
      "Cybex Sirona T i-Size растёт вместе с ребёнком от рождения до 4 лет и поворачивается на 360° для удобной посадки без наклона над салоном. Противоротационная опора и боковая система защиты обеспечивают дополнительную безопасность при боковом ударе.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 46000,
    old_price: null,
    stock_status: "preorder",
    specs: carSeatSpecs("13.5 кг", "0+/I/II (до 105 см)", "ISOFIX + опора", "45–105 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-sirona-t-isize-soho-grey",
    name_ua: "Автокрісло Cybex Sirona T i-Size (Soho Grey)",
    name_ru: "Автокресло Cybex Sirona T i-Size (Soho Grey)",
    description_ua:
      "Cybex Sirona T i-Size росте разом із дитиною від народження до 4 років і обертається на 360° для зручного саджання без нахилу над салоном. Проти-ротаційна опора та бокова система захисту забезпечують додаткову безпеку при боковому ударі.",
    description_ru:
      "Cybex Sirona T i-Size растёт вместе с ребёнком от рождения до 4 лет и поворачивается на 360° для удобной посадки без наклона над салоном. Противоротационная опора и боковая система защиты обеспечивают дополнительную безопасность при боковом ударе.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 46000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("13.5 кг", "0+/I/II (до 105 см)", "ISOFIX + опора", "45–105 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Sirona S2 i-Size (автокрісло, обертове, середній клас) ---
  {
    slug: "cybex-sirona-s2-isize-lava-red",
    name_ua: "Автокрісло Cybex Sirona S2 i-Size (Lava Red)",
    name_ru: "Автокресло Cybex Sirona S2 i-Size (Lava Red)",
    description_ua:
      "Cybex Sirona S2 i-Size — автокрісло середнього класу лінійки Sirona, яке обертається на 360° та встановлюється як проти ходу руху, так і за ним залежно від віку дитини. Лінійний поглинач удару додає захисту без збільшення габаритів крісла.",
    description_ru:
      "Cybex Sirona S2 i-Size — автокресло среднего класса линейки Sirona, которое поворачивается на 360° и устанавливается как против хода движения, так и по ходу в зависимости от возраста ребёнка. Линейный амортизатор удара добавляет защиты без увеличения габаритов кресла.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 38000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("12.8 кг", "0+/I/II (до 105 см)", "ISOFIX + опора", "45–105 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-sirona-s2-isize-soho-grey",
    name_ua: "Автокрісло Cybex Sirona S2 i-Size (Soho Grey)",
    name_ru: "Автокресло Cybex Sirona S2 i-Size (Soho Grey)",
    description_ua:
      "Cybex Sirona S2 i-Size — автокрісло середнього класу лінійки Sirona, яке обертається на 360° та встановлюється як проти ходу руху, так і за ним залежно від віку дитини. Лінійний поглинач удару додає захисту без збільшення габаритів крісла.",
    description_ru:
      "Cybex Sirona S2 i-Size — автокресло среднего класса линейки Sirona, которое поворачивается на 360° и устанавливается как против хода движения, так и по ходу в зависимости от возраста ребёнка. Линейный амортизатор удара добавляет защиты без увеличения габаритов кресла.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 38500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("12.8 кг", "0+/I/II (до 105 см)", "ISOFIX + опора", "45–105 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-sirona-s2-isize-moon-black",
    name_ua: "Автокрісло Cybex Sirona S2 i-Size (Moon Black)",
    name_ru: "Автокресло Cybex Sirona S2 i-Size (Moon Black)",
    description_ua:
      "Cybex Sirona S2 i-Size — автокрісло середнього класу лінійки Sirona, яке обертається на 360° та встановлюється як проти ходу руху, так і за ним залежно від віку дитини. Лінійний поглинач удару додає захисту без збільшення габаритів крісла.",
    description_ru:
      "Cybex Sirona S2 i-Size — автокресло среднего класса линейки Sirona, которое поворачивается на 360° и устанавливается как против хода движения, так и по ходу в зависимости от возраста ребёнка. Линейный амортизатор удара добавляет защиты без увеличения габаритов кресла.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 38500,
    old_price: null,
    stock_status: "out_of_stock",
    specs: carSeatSpecs("12.8 кг", "0+/I/II (до 105 см)", "ISOFIX + опора", "45–105 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Sirona Gi i-Size (автокрісло, універсальна база) ---
  {
    slug: "cybex-sirona-gi-isize-plum",
    name_ua: "Автокрісло Cybex Sirona Gi i-Size (Plum)",
    name_ru: "Автокресло Cybex Sirona Gi i-Size (Plum)",
    description_ua:
      "Cybex Sirona Gi i-Size поєднує обертове крісло з можливістю встановлення на будь-яку базу i-Size, а не лише фірмову. G-подушка безпеки замінює традиційні лямки для найменших і знімається в міру дорослішання дитини.",
    description_ru:
      "Cybex Sirona Gi i-Size сочетает поворотное кресло с возможностью установки на любую базу i-Size, а не только фирменную. G-подушка безопасности заменяет традиционные лямки для самых маленьких и снимается по мере взросления ребёнка.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 44000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("13.1 кг", "I/II (61–105 см)", "будь-яка база i-Size", "61–105 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-sirona-gi-isize-graphite-black",
    name_ua: "Автокрісло Cybex Sirona Gi i-Size (Graphite Black)",
    name_ru: "Автокресло Cybex Sirona Gi i-Size (Graphite Black)",
    description_ua:
      "Cybex Sirona Gi i-Size поєднує обертове крісло з можливістю встановлення на будь-яку базу i-Size, а не лише фірмову. G-подушка безпеки замінює традиційні лямки для найменших і знімається в міру дорослішання дитини.",
    description_ru:
      "Cybex Sirona Gi i-Size сочетает поворотное кресло с возможностью установки на любую базу i-Size, а не только фирменную. G-подушка безопасности заменяет традиционные лямки для самых маленьких и снимается по мере взросления ребёнка.",
    brand: "Cybex",
    category_slug: "car-seats-isize",
    price: 44500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("13.1 кг", "I/II (61–105 см)", "будь-яка база i-Size", "61–105 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Solution B2-Fix+ (бустер) ---
  {
    slug: "cybex-solution-b2-fix-soho-grey",
    name_ua: "Автокрісло-бустер Cybex Solution B2-Fix+ (Soho Grey)",
    name_ru: "Автокресло-бустер Cybex Solution B2-Fix+ (Soho Grey)",
    description_ua:
      "Cybex Solution B2-Fix+ — бустер з фіксованою спинкою для дітей від 3 до 12 років з кріпленням ISOFIX для додаткової стабільності в авто. Підголівник регулюється в 11 положеннях однією рукою одночасно з ремінцями безпеки.",
    description_ru:
      "Cybex Solution B2-Fix+ — бустер с фиксированной спинкой для детей от 3 до 12 лет с креплением ISOFIX для дополнительной стабильности в авто. Подголовник регулируется в 11 положениях одной рукой одновременно с ремнями безопасности.",
    brand: "Cybex",
    category_slug: "car-seats-boosters",
    price: 14000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("4.2 кг", "II/III (100–150 см)", "ISOFIX + ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-solution-b2-fix-lava-red",
    name_ua: "Автокрісло-бустер Cybex Solution B2-Fix+ (Lava Red)",
    name_ru: "Автокресло-бустер Cybex Solution B2-Fix+ (Lava Red)",
    description_ua:
      "Cybex Solution B2-Fix+ — бустер з фіксованою спинкою для дітей від 3 до 12 років з кріпленням ISOFIX для додаткової стабільності в авто. Підголівник регулюється в 11 положеннях однією рукою одночасно з ремінцями безпеки.",
    description_ru:
      "Cybex Solution B2-Fix+ — бустер с фиксированной спинкой для детей от 3 до 12 лет с креплением ISOFIX для дополнительной стабильности в авто. Подголовник регулируется в 11 положениях одной рукой одновременно с ремнями безопасности.",
    brand: "Cybex",
    category_slug: "car-seats-boosters",
    price: 14000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("4.2 кг", "II/III (100–150 см)", "ISOFIX + ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-solution-b2-fix-moon-black",
    name_ua: "Автокрісло-бустер Cybex Solution B2-Fix+ (Moon Black)",
    name_ru: "Автокресло-бустер Cybex Solution B2-Fix+ (Moon Black)",
    description_ua:
      "Cybex Solution B2-Fix+ — бустер з фіксованою спинкою для дітей від 3 до 12 років з кріпленням ISOFIX для додаткової стабільності в авто. Підголівник регулюється в 11 положеннях однією рукою одночасно з ремінцями безпеки.",
    description_ru:
      "Cybex Solution B2-Fix+ — бустер с фиксированной спинкой для детей от 3 до 12 лет с креплением ISOFIX для дополнительной стабильности в авто. Подголовник регулируется в 11 положениях одной рукой одновременно с ремнями безопасности.",
    brand: "Cybex",
    category_slug: "car-seats-boosters",
    price: 14500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("4.2 кг", "II/III (100–150 см)", "ISOFIX + ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Solution T i-Fix (бустер) ---
  {
    slug: "cybex-solution-t-ifix-plum",
    name_ua: "Автокрісло-бустер Cybex Solution T i-Fix (Plum)",
    name_ru: "Автокресло-бустер Cybex Solution T i-Fix (Plum)",
    description_ua:
      "Cybex Solution T i-Fix додає до звичного бустера лінійну систему поглинання удару та глибші бокові крила для кращого захисту голови. Тканина знімається і прасується без спеціального відпарювача.",
    description_ru:
      "Cybex Solution T i-Fix добавляет к привычному бустеру линейную систему поглощения удара и более глубокие боковые крылья для лучшей защиты головы. Ткань снимается и гладится без специального отпаривателя.",
    brand: "Cybex",
    category_slug: "car-seats-boosters",
    price: 19500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("5.1 кг", "II/III (100–150 см)", "ISOFIX + ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-solution-t-ifix-graphite-black",
    name_ua: "Автокрісло-бустер Cybex Solution T i-Fix (Graphite Black)",
    name_ru: "Автокресло-бустер Cybex Solution T i-Fix (Graphite Black)",
    description_ua:
      "Cybex Solution T i-Fix додає до звичного бустера лінійну систему поглинання удару та глибші бокові крила для кращого захисту голови. Тканина знімається і прасується без спеціального відпарювача.",
    description_ru:
      "Cybex Solution T i-Fix добавляет к привычному бустеру линейную систему поглощения удара и более глубокие боковые крылья для лучшей защиты головы. Ткань снимается и гладится без специального отпаривателя.",
    brand: "Cybex",
    category_slug: "car-seats-boosters",
    price: 18000,
    old_price: 20500,
    stock_status: "in_stock",
    specs: carSeatSpecs("5.1 кг", "II/III (100–150 см)", "ISOFIX + ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: true,
  },
  // --- Pallas G i-Size (бустер-трансформер) ---
  {
    slug: "cybex-pallas-g-isize-graphite-black",
    name_ua: "Автокрісло Cybex Pallas G i-Size (Graphite Black)",
    name_ru: "Автокресло Cybex Pallas G i-Size (Graphite Black)",
    description_ua:
      "Cybex Pallas G i-Size розраховане на дітей від 3 до 12 років і трансформується з крісла зі спинкою на бустер без спинки в міру дорослішання дитини. Регулювання по 12 позиціях висоти підголівника підлаштовується під зростання без заміни крісла.",
    description_ru:
      "Cybex Pallas G i-Size рассчитано на детей от 3 до 12 лет и трансформируется из кресла со спинкой в бустер без спинки по мере взросления ребёнка. Регулировка по 12 позициям высоты подголовника подстраивается под рост без замены кресла.",
    brand: "Cybex",
    category_slug: "car-seats-boosters",
    price: 27000,
    old_price: null,
    stock_status: "out_of_stock",
    specs: carSeatSpecs("6.9 кг", "II/III (100–150 см)", "ISOFIX + ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-pallas-g-isize-soho-grey",
    name_ua: "Автокрісло Cybex Pallas G i-Size (Soho Grey)",
    name_ru: "Автокресло Cybex Pallas G i-Size (Soho Grey)",
    description_ua:
      "Cybex Pallas G i-Size розраховане на дітей від 3 до 12 років і трансформується з крісла зі спинкою на бустер без спинки в міру дорослішання дитини. Регулювання по 12 позиціях висоти підголівника підлаштовується під зростання без заміни крісла.",
    description_ru:
      "Cybex Pallas G i-Size рассчитано на детей от 3 до 12 лет и трансформируется из кресла со спинкой в бустер без спинки по мере взросления ребёнка. Регулировка по 12 позициям высоты подголовника подстраивается под рост без замены кресла.",
    brand: "Cybex",
    category_slug: "car-seats-boosters",
    price: 27500,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("6.9 кг", "II/III (100–150 см)", "ISOFIX + ремені авто", "100–150 см"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Бази ISOFIX ---
  {
    slug: "cybex-base-t",
    name_ua: "База ISOFIX Cybex Base T",
    name_ru: "База ISOFIX Cybex Base T",
    description_ua:
      "База Cybex Base T призначена для автокрісла Cloud T i-Size і кріпиться в авто через ISOFIX та третю опорну ногу. Індикатори на базі підтверджують правильність установки перш ніж пристібати дитину.",
    description_ru:
      "База Cybex Base T предназначена для автокресла Cloud T i-Size и крепится в авто через ISOFIX и третью опорную ногу. Индикаторы на базе подтверждают правильность установки, прежде чем пристёгивать ребёнка.",
    brand: "Cybex",
    category_slug: "car-seat-bases",
    price: 15000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("6.8 кг", "сумісна з Cloud T i-Size", "ISOFIX + опорна нога", "—"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-base-one",
    name_ua: "База ISOFIX Cybex Base One",
    name_ru: "База ISOFIX Cybex Base One",
    description_ua:
      "База Cybex Base One підходить для автокрісел Aton B2 і Aton S2, дозволяючи пристібати й відстібати люльку одним рухом без ременів щоразу. Компактні розміри залишають місце для переднього пасажира навіть у невеликому авто.",
    description_ru:
      "База Cybex Base One подходит для автокресел Aton B2 и Aton S2, позволяя пристёгивать и отстёгивать люльку одним движением без ремней каждый раз. Компактные размеры оставляют место для переднего пассажира даже в небольшом авто.",
    brand: "Cybex",
    category_slug: "car-seat-bases",
    price: 13000,
    old_price: null,
    stock_status: "in_stock",
    specs: carSeatSpecs("5.9 кг", "сумісна з Aton B2 / Aton S2", "ISOFIX + опорна нога", "—"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  // --- Аксесуари Cybex ---
  {
    slug: "cybex-raincover",
    name_ua: "Дощовик для колясок Cybex",
    name_ru: "Дождевик для колясок Cybex",
    description_ua:
      "Фірмовий дощовик Cybex пошитий за формою прогулянкових блоків бренду для щільного прилягання без зазорів. Прозорий матеріал не спотворює огляд дитині, а невелика вага не обтяжує складену коляску.",
    description_ru:
      "Фирменный дождевик Cybex скроен по форме прогулочных блоков бренда для плотного прилегания без зазоров. Прозрачный материал не искажает обзор ребёнку, а небольшой вес не утяжеляет сложенную коляску.",
    brand: "Cybex",
    category_slug: "accessories-stroller",
    price: 900,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("ПВХ без фталатів", "Balios S, Eezy S, Mios, Priam", "протирати вологою тканиною"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-cup-holder",
    name_ua: "Підстаканник універсальний Cybex",
    name_ru: "Подстаканник универсальный Cybex",
    description_ua:
      "Підстаканник кріпиться на поручень коляски за лічені секунди й тримає пляшечку або чашку кави без розхитування. Знімається для миття в посудомийній машині.",
    description_ru:
      "Подстаканник крепится на поручень коляски за считаные секунды и удерживает бутылочку или чашку кофе без раскачивания. Снимается для мытья в посудомоечной машине.",
    brand: "Cybex",
    category_slug: "accessories-stroller",
    price: 550,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("пластик + силіконова вставка", "більшість колясок з круглим поручнем", "мити в посудомийній машині"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-sun-canopy",
    name_ua: "Сонцезахисний козирок Cybex",
    name_ru: "Солнцезащитный козырёк Cybex",
    description_ua:
      "Додатковий козирок з UV-захистом кріпиться поверх штатного капюшона і затінює обличчя дитини у сонячні дні. Гнучкий каркас дозволяє налаштувати кут нахилу під висоту сонця.",
    description_ru:
      "Дополнительный козырёк с UV-защитой крепится поверх штатного капюшона и затеняет лицо ребёнка в солнечные дни. Гибкий каркас позволяет настроить угол наклона под высоту солнца.",
    brand: "Cybex",
    category_slug: "accessories-stroller",
    price: 800,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("тканина з UV 50+", "більшість прогулянкових колясок", "протирати вологою тканиною"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-footmuff",
    name_ua: "Конверт фірмовий для коляски Cybex",
    name_ru: "Конверт фирменный для коляски Cybex",
    description_ua:
      "Фірмовий конверт Cybex адаптований під форму прогулянкових блоків бренду і кріпиться без зазорів навколо ременів безпеки. Знімна підкладка дозволяє використовувати конверт як демісезонний або зимовий варіант.",
    description_ru:
      "Фирменный конверт Cybex адаптирован под форму прогулочных блоков бренда и крепится без зазоров вокруг ремней безопасности. Съёмная подкладка позволяет использовать конверт как демисезонный или зимний вариант.",
    brand: "Cybex",
    category_slug: "footmuffs",
    price: 2400,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("плащівка + знімне хутро", "Balios S, Eezy S, Mios, Priam, Talos S", "прання при 30°C"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-travel-bag",
    name_ua: "Дорожня сумка для коляски Cybex",
    name_ru: "Дорожная сумка для коляски Cybex",
    description_ua:
      "Дорожня сумка Cybex для транспортування складеної коляски в літаку чи потязі захищає раму від подряпин і бруду. Щільні ручки та ремінець через плече полегшують перенесення в аеропорту.",
    description_ru:
      "Дорожная сумка Cybex для транспортировки сложенной коляски в самолёте или поезде защищает раму от царапин и грязи. Плотные ручки и ремешок через плечо облегчают переноску в аэропорту.",
    brand: "Cybex",
    category_slug: "accessories-stroller",
    price: 1400,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("щільний поліестер", "більшість складених колясок", "протирати вологою тканиною"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-newborn-insert",
    name_ua: "Вкладиш для новонародженого Cybex",
    name_ru: "Вкладыш для новорождённого Cybex",
    description_ua:
      "Вкладиш для новонародженого Cybex підтримує голову і хребет немовляти в автокріслах групи 0+ до досягнення потрібної ваги. Дихаюча тканина знижує ризик перегріву в теплу пору року.",
    description_ru:
      "Вкладыш для новорождённого Cybex поддерживает голову и позвоночник младенца в автокреслах группы 0+ до достижения нужного веса. Дышащая ткань снижает риск перегрева в тёплое время года.",
    brand: "Cybex",
    category_slug: "accessories-carseat",
    price: 1100,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("бавовна + піна з памʼяттю форми", "автокрісла групи 0+ Cybex", "прання при 30°C"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
  {
    slug: "cybex-stroller-hook",
    name_ua: "Гачок для сумок на коляску Cybex",
    name_ru: "Крючок для сумок на коляску Cybex",
    description_ua:
      "Гачок для сумок Cybex витримує до 5 кг ваги і кріпиться на ручку коляски без інструментів. Складна конструкція дозволяє скласти коляску, не знімаючи гачок з сумками.",
    description_ru:
      "Крючок для сумок Cybex выдерживает до 5 кг веса и крепится на ручку коляски без инструментов. Складная конструкция позволяет сложить коляску, не снимая крючок с сумками.",
    brand: "Cybex",
    category_slug: "accessories-stroller",
    price: 500,
    old_price: null,
    stock_status: "in_stock",
    specs: accessorySpecs("армований пластик", "більшість колясок з поручнем", "протирати вологою тканиною"),
    images: [],
    is_hit: false,
    is_sale: false,
  },
];
